import type {CardData} from "$lib/types/card";

const cards: CardData[] = [
    {
        name: "Mysterious Elf",
        id: "142",
        deck: "neutral",
        row: "close",
        strength: 0,
        filename: "mysterious_elf",
        count: 1,
        abilities: [
            "hero",
            "spy",
        ],
    },
    {
        name: "Decoy",
        id: "1",
        deck: "special",
        row: "",
        strength: 0,
        filename: "decoy",
        count: 3,
        abilities: [
            "decoy",
        ],
    },
    {
        name: "Biting Frost",
        id: "4",
        deck: "weather",
        row: "",
        strength: 0,
        filename: "frost",
        count: 3,
        abilities: [
            "frost",
        ],
    },
    {
        name: "Cirilla Fiona Elen Riannon",
        id: "139",
        deck: "neutral",
        row: "close",
        strength: 15,
        filename: "ciri",
        count: 1,
        abilities: [
            "hero",
        ],
    },
    {
        name: "Clear Weather",
        id: "7",
        deck: "weather",
        row: "",
        strength: 0,
        filename: "clear",
        count: 2,
        abilities: [
            "clear",
        ],
    },
    {
        name: "Commander's Horn",
        id: "2",
        deck: "special",
        row: "",
        strength: 0,
        filename: "horn",
        count: 3,
        abilities: [
            "horn",
        ],
    },
    {
        name: "Dandelion",
        id: "11",
        deck: "neutral",
        row: "close",
        strength: 2,
        filename: "dandelion",
        count: 1,
        abilities: [
            "horn",
        ],
    },
    {
        name: "Emiel Regis Rohellec Terzieff",
        id: "",
        deck: "neutral",
        row: "close",
        strength: 5,
        filename: "emiel",
        count: 1,
        abilities: [],
    },
    {
        name: "Geralt of Rivia",
        id: "138",
        deck: "neutral",
        row: "close",
        strength: 15,
        filename: "geralt",
        count: 1,
        abilities: [
            "hero",
        ],
    },
    {
        name: "Impenetrable Fog",
        id: "5",
        deck: "weather",
        row: "",
        strength: 0,
        filename: "fog",
        count: 3,
        abilities: [
            "fog",
        ],
    },
    {
        name: "Scorch",
        id: "3",
        deck: "special",
        row: "",
        strength: 0,
        filename: "scorch",
        count: 3,
        abilities: [
            "scorch",
        ],
    },
    {
        name: "Torrential Rain",
        id: "6",
        deck: "weather",
        row: "",
        strength: 0,
        filename: "rain",
        count: 2,
        abilities: [
            "rain",
        ],
    },
    {
        name: "Triss Merigold",
        id: "141",
        deck: "neutral",
        row: "close",
        strength: 7,
        filename: "triss",
        count: 1,
        abilities: [
            "hero",
        ],
    },
    {
        name: "Vesemir",
        id: "9",
        deck: "neutral",
        row: "close",
        strength: 6,
        filename: "vesemir",
        count: 1,
        abilities: [],
    },
    {
        name: "Villentretenmerth",
        id: "8",
        deck: "neutral",
        row: "close",
        strength: 7,
        filename: "villen",
        count: 1,
        abilities: [
            "scorch_c",
        ],
    },
    {
        name: "Yennefer of Vengerberg",
        id: "140",
        deck: "neutral",
        row: "ranged",
        strength: 7,
        filename: "yennefer",
        count: 1,
        abilities: [
            "hero",
            "medic",
        ],
    },
    {
        name: "Zoltan Chivay",
        id: "10",
        deck: "neutral",
        row: "close",
        strength: 5,
        filename: "zoltan",
        count: 1,
        abilities: [],
    },
    {
        name: "Olgierd von Everec",
        id: "",
        deck: "neutral",
        row: "agile",
        strength: 6,
        filename: "olgierd",
        count: 1,
        abilities: [
            "morale",
        ],
    },
    {
        name: "Gaunter O'Dimm",
        id: "",
        deck: "neutral",
        row: "siege",
        strength: 2,
        filename: "gaunter_odimm",
        count: 1,
        abilities: [
            "muster",
        ],
    },
    {
        name: "Gaunter O'Dimm - Darkness",
        id: "",
        deck: "neutral",
        row: "ranged",
        strength: 4,
        filename: "gaunter_odimm_darkness",
        count: 3,
        abilities: [
            "muster",
        ],
    },
    {
        name: "Cow",
        id: "",
        deck: "neutral",
        row: "ranged",
        strength: 0,
        filename: "cow",
        count: 1,
        abilities: [
            "avenger",
        ],
    },
    {
        name: "Bovine Defense Force",
        id: "",
        deck: "neutral",
        row: "close",
        strength: 8,
        filename: "chort",
        count: 0,
        abilities: [],
    },
    {
        name: "Foltest - King of Temeria",
        id: "5",
        deck: "realms",
        row: "leader",
        strength: 0,
        filename: "foltest_silver",
        count: 1,
        abilities: [
            "foltest_king",
        ],
    },
    {
        name: "Foltest - Lord Commander of the North",
        id: "8",
        deck: "realms",
        row: "leader",
        strength: 0,
        filename: "foltest_gold",
        count: 1,
        abilities: [
            "foltest_lord",
        ],
    },
    {
        name: "Foltest - The Siegemaster",
        id: "6",
        deck: "realms",
        row: "leader",
        strength: 0,
        filename: "foltest_copper",
        count: 1,
        abilities: [
            "foltest_siegemaster",
        ],
    },
    {
        name: "Foltest - The Steel-Forged",
        id: "7",
        deck: "realms",
        row: "leader",
        strength: 0,
        filename: "foltest_bronze",
        count: 1,
        abilities: [
            "foltest_steelforged",
        ],
    },
    {
        name: "Foltest - Son of Medell",
        id: "",
        deck: "realms",
        row: "leader",
        strength: 0,
        filename: "foltest_son_of_medell",
        count: 1,
        abilities: [
            "foltest_son",
        ],
    },
    {
        name: "Ballista",
        id: "79",
        deck: "realms",
        row: "siege",
        strength: 6,
        filename: "ballista",
        count: 1,
        abilities: [],
    },
    {
        name: "Blue Stripes Commando",
        id: "92",
        deck: "realms",
        row: "close",
        strength: 4,
        filename: "blue_stripes",
        count: 3,
        abilities: [
            "bond",
        ],
    },
    {
        name: "Catapult",
        id: "75",
        deck: "realms",
        row: "siege",
        strength: 8,
        filename: "catapult_1",
        count: 2,
        abilities: [
            "bond",
        ],
    },
    {
        name: "Crinfrid Reavers Dragon Hunter",
        id: "87",
        deck: "realms",
        row: "ranged",
        strength: 5,
        filename: "crinfrid",
        count: 3,
        abilities: [
            "bond",
        ],
    },
    {
        name: "Dethmold",
        id: "76",
        deck: "realms",
        row: "ranged",
        strength: 6,
        filename: "dethmold",
        count: 1,
        abilities: [],
    },
    {
        name: "Dun Banner Medic",
        id: "88",
        deck: "realms",
        row: "siege",
        strength: 5,
        filename: "banner_nurse",
        count: 1,
        abilities: [
            "medic",
        ],
    },
    {
        name: "Esterad Thyssen",
        id: "11",
        deck: "realms",
        row: "close",
        strength: 10,
        filename: "esterad",
        count: 1,
        abilities: [
            "hero",
        ],
    },
    {
        name: "John Natalis",
        id: "10",
        deck: "realms",
        row: "close",
        strength: 10,
        filename: "natalis",
        count: 1,
        abilities: [
            "hero",
        ],
    },
    {
        name: "Kaedweni Siege Expert",
        id: "98",
        deck: "realms",
        row: "siege",
        strength: 1,
        filename: "kaedwen_siege",
        count: 1,
        abilities: [
            "morale",
        ],
    },
    {
        name: "Kaedweni Siege Expert",
        id: "99",
        deck: "realms",
        row: "siege",
        strength: 1,
        filename: "kaedwen_siege_1",
        count: 1,
        abilities: [
            "morale",
        ],
    },
    {
        name: "Kaedweni Siege Expert",
        id: "100",
        deck: "realms",
        row: "siege",
        strength: 1,
        filename: "kaedwen_siege_2",
        count: 1,
        abilities: [
            "morale",
        ],
    },
    {
        name: "Keira Metz",
        id: "84",
        deck: "realms",
        row: "ranged",
        strength: 5,
        filename: "keira",
        count: 1,
        abilities: [],
    },
    {
        name: "Philippa Eilhart",
        id: "12",
        deck: "realms",
        row: "ranged",
        strength: 10,
        filename: "philippa",
        count: 1,
        abilities: [
            "hero",
        ],
    },
    {
        name: "Poor Fucking Infantry",
        id: "95",
        deck: "realms",
        row: "close",
        strength: 1,
        filename: "poor_infantry",
        count: 4,
        abilities: [
            "bond",
        ],
    },
    {
        name: "Prince Stennis",
        id: "86",
        deck: "realms",
        row: "close",
        strength: 5,
        filename: "stennis",
        count: 1,
        abilities: [
            "spy",
        ],
    },
    {
        name: "Redanian Foot Soldier",
        id: "96",
        deck: "realms",
        row: "close",
        strength: 1,
        filename: "redania",
        count: 1,
        abilities: [],
    },
    {
        name: "Redanian Foot Soldier",
        id: "97",
        deck: "realms",
        row: "close",
        strength: 1,
        filename: "redania_1",
        count: 1,
        abilities: [],
    },
    {
        name: "Sheldon Skaggs",
        id: "91",
        deck: "realms",
        row: "ranged",
        strength: 4,
        filename: "sheldon",
        count: 1,
        abilities: [],
    },
    {
        name: "Siege Tower",
        id: "81",
        deck: "realms",
        row: "siege",
        strength: 6,
        filename: "siege_tower",
        count: 1,
        abilities: [],
    },
    {
        name: "Siegfried of Denesle",
        id: "83",
        deck: "realms",
        row: "close",
        strength: 5,
        filename: "siegfried",
        count: 1,
        abilities: [],
    },
    {
        name: "Sigismund Dijkstra",
        id: "89",
        deck: "realms",
        row: "close",
        strength: 4,
        filename: "dijkstra",
        count: 1,
        abilities: [
            "spy",
        ],
    },
    {
        name: "Síle de Tansarville",
        id: "85",
        deck: "realms",
        row: "ranged",
        strength: 5,
        filename: "sheala",
        count: 1,
        abilities: [],
    },
    {
        name: "Thaler",
        id: "94",
        deck: "realms",
        row: "siege",
        strength: 1,
        filename: "thaler",
        count: 1,
        abilities: [
            "spy",
        ],
    },
    {
        name: "Sabrina Glevissig",
        id: "90",
        deck: "realms",
        row: "ranged",
        strength: 4,
        filename: "sabrina",
        count: 1,
        abilities: [],
    },
    {
        name: "Vernon Roche",
        id: "9",
        deck: "realms",
        row: "close",
        strength: 10,
        filename: "vernon",
        count: 1,
        abilities: [
            "hero",
        ],
    },
    {
        name: "Ves",
        id: "82",
        deck: "realms",
        row: "close",
        strength: 5,
        filename: "ves",
        count: 1,
        abilities: [],
    },
    {
        name: "Yarpen Zigrin",
        id: "93",
        deck: "realms",
        row: "close",
        strength: 2,
        filename: "yarpen",
        count: 1,
        abilities: [],
    },
    {
        name: "Trebuchet",
        id: "77",
        deck: "realms",
        row: "siege",
        strength: 6,
        filename: "trebuchet",
        count: 1,
        abilities: [],
    },
    {
        name: "Trebuchet",
        id: "78",
        deck: "realms",
        row: "siege",
        strength: 6,
        filename: "trebuchet_1",
        count: 1,
        abilities: [],
    },
    {
        name: "Emhyr var Emreis - His Imperial Majesty",
        id: "1",
        deck: "nilfgaard",
        row: "leader",
        strength: 0,
        filename: "emhyr_silver",
        count: 1,
        abilities: [
            "emhyr_imperial",
        ],
    },
    {
        name: "Emhyr var Emreis - Emperor of Nilfgaard",
        id: "2",
        deck: "nilfgaard",
        row: "leader",
        strength: 0,
        filename: "emhyr_copper",
        count: 1,
        abilities: [
            "emhyr_emperor",
        ],
    },
    {
        name: "Emhyr var Emreis - the White Flame",
        id: "3",
        deck: "nilfgaard",
        row: "leader",
        strength: 0,
        filename: "emhyr_bronze",
        count: 1,
        abilities: [
            "emhyr_whiteflame",
        ],
    },
    {
        name: "Emhyr var Emreis - The Relentless",
        id: "4",
        deck: "nilfgaard",
        row: "leader",
        strength: 0,
        filename: "emhyr_gold",
        count: 1,
        abilities: [
            "emhyr_relentless",
        ],
    },
    {
        name: "Emhyr var Emreis - Invader of the North",
        id: "",
        deck: "nilfgaard",
        row: "leader",
        strength: 0,
        filename: "emhyr_invader_of_the_north",
        count: 1,
        abilities: [
            "emhyr_invader",
        ],
    },
    {
        name: "Albrich",
        id: "68",
        deck: "nilfgaard",
        row: "ranged",
        strength: 2,
        filename: "albrich",
        count: 1,
        abilities: [],
    },
    {
        name: "Assire var Anahid",
        id: "52",
        deck: "nilfgaard",
        row: "ranged",
        strength: 6,
        filename: "assire",
        count: 1,
        abilities: [],
    },
    {
        name: "Black Infantry Archer",
        id: "47",
        deck: "nilfgaard",
        row: "ranged",
        strength: 10,
        filename: "black_archer",
        count: 1,
        abilities: [],
    },
    {
        name: "Black Infantry Archer",
        id: "48",
        deck: "nilfgaard",
        row: "ranged",
        strength: 10,
        filename: "black_archer_1",
        count: 1,
        abilities: [],
    },
    {
        name: "Cahir Mawr Dyffryn aep Ceallach",
        id: "54",
        deck: "nilfgaard",
        row: "close",
        strength: 6,
        filename: "cahir",
        count: 1,
        abilities: [],
    },
    {
        name: "Cynthia",
        id: "60",
        deck: "nilfgaard",
        row: "ranged",
        strength: 4,
        filename: "cynthia",
        count: 1,
        abilities: [],
    },
    {
        name: "Etolian Auxiliary Archers",
        id: "72",
        deck: "nilfgaard",
        row: "ranged",
        strength: 1,
        filename: "archer_support",
        count: 1,
        abilities: [
            "medic",
        ],
    },
    {
        name: "Etolian Auxiliary Archers",
        id: "73",
        deck: "nilfgaard",
        row: "ranged",
        strength: 1,
        filename: "archer_support_1",
        count: 1,
        abilities: [
            "medic",
        ],
    },
    {
        name: "Fringilla Vigo",
        id: "53",
        deck: "nilfgaard",
        row: "ranged",
        strength: 6,
        filename: "fringilla",
        count: 1,
        abilities: [],
    },
    {
        name: "Heavy Zerrikanian Fire Scorpion",
        id: "49",
        deck: "nilfgaard",
        row: "siege",
        strength: 10,
        filename: "heavy_zerri",
        count: 1,
        abilities: [],
    },
    {
        name: "Impera Brigade Guard",
        id: "67",
        deck: "nilfgaard",
        row: "close",
        strength: 3,
        filename: "imperal_brigade",
        count: 4,
        abilities: [
            "bond",
        ],
    },
    {
        name: "Letho of Gulet",
        id: "147",
        deck: "nilfgaard",
        row: "close",
        strength: 10,
        filename: "letho",
        count: 1,
        abilities: [
            "hero",
        ],
    },
    {
        name: "Menno Coehoorn",
        id: "148",
        deck: "nilfgaard",
        row: "close",
        strength: 10,
        filename: "menno",
        count: 1,
        abilities: [
            "hero",
            "medic",
        ],
    },
    {
        name: "Morteisen",
        id: "64",
        deck: "nilfgaard",
        row: "close",
        strength: 3,
        filename: "morteisen",
        count: 1,
        abilities: [],
    },
    {
        name: "Morvran Voorhis",
        id: "149",
        deck: "nilfgaard",
        row: "siege",
        strength: 10,
        filename: "moorvran",
        count: 1,
        abilities: [
            "hero",
        ],
    },
    {
        name: "Nausicaa Cavalry Rider",
        id: "71",
        deck: "nilfgaard",
        row: "close",
        strength: 2,
        filename: "nauzicaa_2",
        count: 3,
        abilities: [
            "bond",
        ],
    },
    {
        name: "Puttkammer",
        id: "66",
        deck: "nilfgaard",
        row: "ranged",
        strength: 3,
        filename: "puttkammer",
        count: 1,
        abilities: [],
    },
    {
        name: "Rainfarn",
        id: "61",
        deck: "nilfgaard",
        row: "close",
        strength: 4,
        filename: "rainfarn",
        count: 1,
        abilities: [],
    },
    {
        name: "Renuald aep Matsen",
        id: "56",
        deck: "nilfgaard",
        row: "ranged",
        strength: 5,
        filename: "renuald",
        count: 1,
        abilities: [],
    },
    {
        name: "Rotten Mangonel",
        id: "65",
        deck: "nilfgaard",
        row: "siege",
        strength: 3,
        filename: "rotten",
        count: 1,
        abilities: [],
    },
    {
        name: "Shilard Fitz-Oesterlen",
        id: "51",
        deck: "nilfgaard",
        row: "close",
        strength: 7,
        filename: "shilard",
        count: 1,
        abilities: [
            "spy",
        ],
    },
    {
        name: "Siege Engineer",
        id: "55",
        deck: "nilfgaard",
        row: "siege",
        strength: 6,
        filename: "siege_engineer",
        count: 1,
        abilities: [],
    },
    {
        name: "Siege Technician",
        id: "74",
        deck: "nilfgaard",
        row: "siege",
        strength: 0,
        filename: "siege_support",
        count: 1,
        abilities: [
            "medic",
        ],
    },
    {
        name: "Stefan Skellen",
        id: "50",
        deck: "nilfgaard",
        row: "close",
        strength: 9,
        filename: "stefan",
        count: 1,
        abilities: [
            "spy",
        ],
    },
    {
        name: "Sweers",
        id: "69",
        deck: "nilfgaard",
        row: "ranged",
        strength: 2,
        filename: "sweers",
        count: 1,
        abilities: [],
    },
    {
        name: "Tibor Eggebracht",
        id: "150",
        deck: "nilfgaard",
        row: "ranged",
        strength: 10,
        filename: "tibor",
        count: 1,
        abilities: [
            "hero",
        ],
    },
    {
        name: "Vanhemar",
        id: "62",
        deck: "nilfgaard",
        row: "ranged",
        strength: 4,
        filename: "vanhemar",
        count: 1,
        abilities: [],
    },
    {
        name: "Vattier de Rideaux",
        id: "63",
        deck: "nilfgaard",
        row: "close",
        strength: 4,
        filename: "vattier",
        count: 1,
        abilities: [
            "spy",
        ],
    },
    {
        name: "Vreemde",
        id: "70",
        deck: "nilfgaard",
        row: "close",
        strength: 2,
        filename: "vreemde",
        count: 1,
        abilities: [],
    },
    {
        name: "Young Emissary",
        id: "58",
        deck: "nilfgaard",
        row: "close",
        strength: 5,
        filename: "young_emissary",
        count: 1,
        abilities: [
            "bond",
        ],
    },
    {
        name: "Young Emissary",
        id: "59",
        deck: "nilfgaard",
        row: "close",
        strength: 5,
        filename: "young_emissary_1",
        count: 1,
        abilities: [
            "bond",
        ],
    },
    {
        name: "Zerrikanian Fire Scorpion",
        id: "57",
        deck: "nilfgaard",
        row: "siege",
        strength: 5,
        filename: "zerri",
        count: 1,
        abilities: [],
    },
    {
        name: "Eredin - Commander of the Red Riders",
        id: "134",
        deck: "monsters",
        row: "leader",
        strength: 0,
        filename: "eredin_silver",
        count: 1,
        abilities: [
            "eredin_commander",
        ],
    },
    {
        name: "Eredin - Bringer of Death",
        id: "136",
        deck: "monsters",
        row: "leader",
        strength: 0,
        filename: "eredin_bronze",
        count: 1,
        abilities: [
            "eredin_bringer_of_death",
        ],
    },
    {
        name: "Eredin - Destroyer of Worlds",
        id: "137",
        deck: "monsters",
        row: "leader",
        strength: 0,
        filename: "eredin_gold",
        count: 1,
        abilities: [
            "eredin_destroyer",
        ],
    },
    {
        name: "Eredin - King of the Wild Hunt",
        id: "135",
        deck: "monsters",
        row: "leader",
        strength: 0,
        filename: "eredin_copper",
        count: 1,
        abilities: [
            "eredin_king",
        ],
    },
    {
        name: "Eredin Bréacc Glas - The Treacherous",
        id: "",
        deck: "monsters",
        row: "leader",
        strength: 0,
        filename: "eredin_the_treacherous",
        count: 1,
        abilities: [
            "eredin_treacherous",
        ],
    },
    {
        name: "Arachas ",
        id: "27",
        deck: "monsters",
        row: "close",
        strength: 4,
        filename: "arachas",
        count: 1,
        abilities: [
            "muster",
        ],
    },
    {
        name: "Arachas ",
        id: "28",
        deck: "monsters",
        row: "close",
        strength: 4,
        filename: "arachas_1",
        count: 1,
        abilities: [
            "muster",
        ],
    },
    {
        name: "Arachas ",
        id: "29",
        deck: "monsters",
        row: "close",
        strength: 4,
        filename: "arachas_2",
        count: 1,
        abilities: [
            "muster",
        ],
    },
    {
        name: "Arachas- Behemoth",
        id: "15",
        deck: "monsters",
        row: "siege",
        strength: 6,
        filename: "arachas_behemoth",
        count: 1,
        abilities: [
            "muster",
        ],
    },
    {
        name: "Botchling",
        id: "26",
        deck: "monsters",
        row: "close",
        strength: 4,
        filename: "poroniec",
        count: 1,
        abilities: [],
    },
    {
        name: "Celaeno Harpy",
        id: "38",
        deck: "monsters",
        row: "agile",
        strength: 2,
        filename: "celaeno_harpy",
        count: 1,
        abilities: [],
    },
    {
        name: "Cockatrice",
        id: "36",
        deck: "monsters",
        row: "ranged",
        strength: 2,
        filename: "cockatrice",
        count: 1,
        abilities: [],
    },
    {
        name: "Crone - Brewess",
        id: "16",
        deck: "monsters",
        row: "close",
        strength: 6,
        filename: "witch_velen",
        count: 1,
        abilities: [
            "muster",
        ],
    },
    {
        name: "Crone - Weavess",
        id: "17",
        deck: "monsters",
        row: "close",
        strength: 6,
        filename: "witch_velen_1",
        count: 1,
        abilities: [
            "muster",
        ],
    },
    {
        name: "Crone - Whispess",
        id: "18",
        deck: "monsters",
        row: "close",
        strength: 6,
        filename: "witch_velen_2",
        count: 1,
        abilities: [
            "muster",
        ],
    },
    {
        name: "Draug",
        id: "143",
        deck: "monsters",
        row: "close",
        strength: 10,
        filename: "draug",
        count: 1,
        abilities: [
            "hero",
        ],
    },
    {
        name: "Earth Elemental",
        id: "12",
        deck: "monsters",
        row: "siege",
        strength: 6,
        filename: "earth_elemental",
        count: 1,
        abilities: [],
    },
    {
        name: "Endrega",
        id: "34",
        deck: "monsters",
        row: "ranged",
        strength: 2,
        filename: "endrega",
        count: 1,
        abilities: [],
    },
    {
        name: "Fiend",
        id: "13",
        deck: "monsters",
        row: "close",
        strength: 6,
        filename: "fiend",
        count: 1,
        abilities: [],
    },
    {
        name: "Fire Elemental",
        id: "14",
        deck: "monsters",
        row: "siege",
        strength: 6,
        filename: "fire_elemental",
        count: 1,
        abilities: [],
    },
    {
        name: "Foglet",
        id: "39",
        deck: "monsters",
        row: "close",
        strength: 2,
        filename: "fogling",
        count: 1,
        abilities: [],
    },
    {
        name: "Forktail",
        id: "19",
        deck: "monsters",
        row: "close",
        strength: 5,
        filename: "forktail",
        count: 1,
        abilities: [],
    },
    {
        name: "Frightener",
        id: "23",
        deck: "monsters",
        row: "close",
        strength: 5,
        filename: "frightener",
        count: 1,
        abilities: [],
    },
    {
        name: "Gargoyle",
        id: "37",
        deck: "monsters",
        row: "ranged",
        strength: 2,
        filename: "gargoyle",
        count: 1,
        abilities: [],
    },
    {
        name: "Ghoul",
        id: "44",
        deck: "monsters",
        row: "close",
        strength: 1,
        filename: "ghoul",
        count: 1,
        abilities: [
            "muster",
        ],
    },
    {
        name: "Ghoul",
        id: "45",
        deck: "monsters",
        row: "close",
        strength: 1,
        filename: "ghoul_1",
        count: 1,
        abilities: [
            "muster",
        ],
    },
    {
        name: "Ghoul",
        id: "46",
        deck: "monsters",
        row: "close",
        strength: 1,
        filename: "ghoul_2",
        count: 1,
        abilities: [
            "muster",
        ],
    },
    {
        name: "Grave Hag",
        id: "25",
        deck: "monsters",
        row: "ranged",
        strength: 5,
        filename: "gravehag",
        count: 1,
        abilities: [],
    },
    {
        name: "Griffin",
        id: "21",
        deck: "monsters",
        row: "close",
        strength: 5,
        filename: "gryffin",
        count: 1,
        abilities: [],
    },
    {
        name: "Harpy",
        id: "35",
        deck: "monsters",
        row: "agile",
        strength: 2,
        filename: "harpy",
        count: 1,
        abilities: [],
    },
    {
        name: "Ice Giant",
        id: "24",
        deck: "monsters",
        row: "siege",
        strength: 5,
        filename: "frost_giant",
        count: 1,
        abilities: [],
    },
    {
        name: "Imlerith",
        id: "144",
        deck: "monsters",
        row: "close",
        strength: 10,
        filename: "imlerith",
        count: 1,
        abilities: [
            "hero",
        ],
    },
    {
        name: "Kayran",
        id: "146",
        deck: "monsters",
        row: "agile",
        strength: 8,
        filename: "kayran",
        count: 1,
        abilities: [
            "hero",
            "morale",
        ],
    },
    {
        name: "Leshen",
        id: "145",
        deck: "monsters",
        row: "ranged",
        strength: 10,
        filename: "leshen",
        count: 1,
        abilities: [
            "hero",
        ],
    },
    {
        name: "Nekker",
        id: "41",
        deck: "monsters",
        row: "close",
        strength: 2,
        filename: "nekker",
        count: 1,
        abilities: [
            "muster",
        ],
    },
    {
        name: "Nekker",
        id: "42",
        deck: "monsters",
        row: "close",
        strength: 2,
        filename: "nekker_1",
        count: 1,
        abilities: [
            "muster",
        ],
    },
    {
        name: "Nekker",
        id: "43",
        deck: "monsters",
        row: "close",
        strength: 2,
        filename: "nekker_2",
        count: 1,
        abilities: [
            "muster",
        ],
    },
    {
        name: "Plague Maiden",
        id: "20",
        deck: "monsters",
        row: "close",
        strength: 5,
        filename: "mighty_maiden",
        count: 1,
        abilities: [],
    },
    {
        name: "Vampire - Bruxa",
        id: "33",
        deck: "monsters",
        row: "close",
        strength: 4,
        filename: "bruxa",
        count: 1,
        abilities: [
            "muster",
        ],
    },
    {
        name: "Vampire - Ekimmara",
        id: "30",
        deck: "monsters",
        row: "close",
        strength: 4,
        filename: "ekkima",
        count: 1,
        abilities: [
            "muster",
        ],
    },
    {
        name: "Vampire - Fleder",
        id: "31",
        deck: "monsters",
        row: "close",
        strength: 4,
        filename: "fleder",
        count: 1,
        abilities: [
            "muster",
        ],
    },
    {
        name: "Vampire - Garkain",
        id: "32",
        deck: "monsters",
        row: "close",
        strength: 4,
        filename: "garkain",
        count: 1,
        abilities: [
            "muster",
        ],
    },
    {
        name: "Vampire - Katakan",
        id: "",
        deck: "monsters",
        row: "close",
        strength: 5,
        filename: "katakan",
        count: 1,
        abilities: [
            "muster",
        ],
    },
    {
        name: "Werewolf",
        id: "22",
        deck: "monsters",
        row: "close",
        strength: 5,
        filename: "werewolf",
        count: 1,
        abilities: [],
    },
    {
        name: "Wyvern",
        id: "40",
        deck: "monsters",
        row: "ranged",
        strength: 2,
        filename: "wyvern",
        count: 1,
        abilities: [],
    },
    {
        name: "Toad",
        id: "",
        deck: "monsters",
        row: "ranged",
        strength: 7,
        filename: "toad",
        count: 1,
        abilities: [
            "scorch_r",
        ],
    },
    {
        name: "Francesca Findabair - Queen of Dol Blathanna",
        id: "13",
        deck: "scoiatael",
        row: "leader",
        strength: 0,
        filename: "francesca_silver",
        count: 1,
        abilities: [
            "francesca_queen",
        ],
    },
    {
        name: "Francesca Findabair - the Beautiful",
        id: "14",
        deck: "scoiatael",
        row: "leader",
        strength: 0,
        filename: "francesca_gold",
        count: 1,
        abilities: [
            "francesca_beautiful",
        ],
    },
    {
        name: "Francesca Findabair - Daisy of the Valley",
        id: "15",
        deck: "scoiatael",
        row: "leader",
        strength: 0,
        filename: "francesca_copper",
        count: 1,
        abilities: [
            "francesca_daisy",
        ],
    },
    {
        name: "Francesca Findabair - Pureblood Elf",
        id: "16",
        deck: "scoiatael",
        row: "leader",
        strength: 0,
        filename: "francesca_bronze",
        count: 1,
        abilities: [
            "francesca_pureblood",
        ],
    },
    {
        name: "Francesca Findabair - Hope of the Aen Seidhe",
        id: "",
        deck: "scoiatael",
        row: "leader",
        strength: 0,
        filename: "francesca_hope_of_the_aen_seidhe",
        count: 1,
        abilities: [
            "francesca_hope",
        ],
    },
    {
        name: "Ciaran aep Easnillien",
        id: "122",
        deck: "scoiatael",
        row: "agile",
        strength: 3,
        filename: "ciaran",
        count: 1,
        abilities: [],
    },
    {
        name: "Barclay Els",
        id: "106",
        deck: "scoiatael",
        row: "agile",
        strength: 6,
        filename: "barclay",
        count: 1,
        abilities: [],
    },
    {
        name: "Dennis Cranmer",
        id: "102",
        deck: "scoiatael",
        row: "close",
        strength: 6,
        filename: "dennis",
        count: 1,
        abilities: [],
    },
    {
        name: "Dol Blathanna Archer",
        id: "121",
        deck: "scoiatael",
        row: "ranged",
        strength: 4,
        filename: "dol_archer",
        count: 1,
        abilities: [],
    },
    {
        name: "Dol Blathanna Scout",
        id: "107",
        deck: "scoiatael",
        row: "agile",
        strength: 6,
        filename: "dol_infantry",
        count: 1,
        abilities: [],
    },
    {
        name: "Dol Blathanna Scout",
        id: "108",
        deck: "scoiatael",
        row: "agile",
        strength: 6,
        filename: "dol_infantry_1",
        count: 1,
        abilities: [],
    },
    {
        name: "Dol Blathanna Scout",
        id: "109",
        deck: "scoiatael",
        row: "agile",
        strength: 6,
        filename: "dol_infantry_2",
        count: 1,
        abilities: [],
    },
    {
        name: "Dwarven Skirmisher",
        id: "123",
        deck: "scoiatael",
        row: "close",
        strength: 3,
        filename: "dwarf",
        count: 1,
        abilities: [
            "muster",
        ],
    },
    {
        name: "Dwarven Skirmisher",
        id: "124",
        deck: "scoiatael",
        row: "close",
        strength: 3,
        filename: "dwarf_1",
        count: 1,
        abilities: [
            "muster",
        ],
    },
    {
        name: "Dwarven Skirmisher",
        id: "125",
        deck: "scoiatael",
        row: "close",
        strength: 3,
        filename: "dwarf_2",
        count: 1,
        abilities: [
            "muster",
        ],
    },
    {
        name: "Eithné",
        id: "17",
        deck: "scoiatael",
        row: "ranged",
        strength: 10,
        filename: "eithne",
        count: 1,
        abilities: [
            "hero",
        ],
    },
    {
        name: "Elven Skirmisher",
        id: "127",
        deck: "scoiatael",
        row: "ranged",
        strength: 2,
        filename: "elf_skirmisher",
        count: 1,
        abilities: [
            "muster",
        ],
    },
    {
        name: "Elven Skirmisher",
        id: "128",
        deck: "scoiatael",
        row: "ranged",
        strength: 2,
        filename: "elf_skirmisher_1",
        count: 1,
        abilities: [
            "muster",
        ],
    },
    {
        name: "Elven Skirmisher",
        id: "129",
        deck: "scoiatael",
        row: "ranged",
        strength: 2,
        filename: "elf_skirmisher_2",
        count: 1,
        abilities: [
            "muster",
        ],
    },
    {
        name: "Filavandrel aen Fidhail",
        id: "104",
        deck: "scoiatael",
        row: "agile",
        strength: 6,
        filename: "filavandrel",
        count: 1,
        abilities: [],
    },
    {
        name: "Havekar Healer",
        id: "131",
        deck: "scoiatael",
        row: "ranged",
        strength: 0,
        filename: "havekar_nurse",
        count: 1,
        abilities: [
            "medic",
        ],
    },
    {
        name: "Havekar Healer",
        id: "132",
        deck: "scoiatael",
        row: "ranged",
        strength: 0,
        filename: "havekar_nurse_1",
        count: 1,
        abilities: [
            "medic",
        ],
    },
    {
        name: "Havekar Healer",
        id: "133",
        deck: "scoiatael",
        row: "ranged",
        strength: 0,
        filename: "havekar_nurse_2",
        count: 1,
        abilities: [
            "medic",
        ],
    },
    {
        name: "Havekar Smuggler",
        id: "110",
        deck: "scoiatael",
        row: "close",
        strength: 5,
        filename: "havekar_support",
        count: 1,
        abilities: [
            "muster",
        ],
    },
    {
        name: "Havekar Smuggler",
        id: "111",
        deck: "scoiatael",
        row: "close",
        strength: 5,
        filename: "havekar_support_1",
        count: 1,
        abilities: [
            "muster",
        ],
    },
    {
        name: "Havekar Smuggler",
        id: "112",
        deck: "scoiatael",
        row: "close",
        strength: 5,
        filename: "havekar_support_2",
        count: 1,
        abilities: [
            "muster",
        ],
    },
    {
        name: "Ida Emean aep Sivney",
        id: "103",
        deck: "scoiatael",
        row: "ranged",
        strength: 6,
        filename: "ida",
        count: 1,
        abilities: [],
    },
    {
        name: "Iorveth",
        id: "20",
        deck: "scoiatael",
        row: "ranged",
        strength: 10,
        filename: "iorveth",
        count: 1,
        abilities: [
            "hero",
        ],
    },
    {
        name: "Isengrim Faoiltiarna",
        id: "19",
        deck: "scoiatael",
        row: "close",
        strength: 10,
        filename: "isengrim",
        count: 1,
        abilities: [
            "hero",
            "morale",
        ],
    },
    {
        name: "Mahakaman Defender",
        id: "115",
        deck: "scoiatael",
        row: "close",
        strength: 5,
        filename: "mahakam",
        count: 1,
        abilities: [],
    },
    {
        name: "Mahakaman Defender",
        id: "116",
        deck: "scoiatael",
        row: "close",
        strength: 5,
        filename: "mahakam_1",
        count: 1,
        abilities: [],
    },
    {
        name: "Mahakaman Defender",
        id: "117",
        deck: "scoiatael",
        row: "close",
        strength: 5,
        filename: "mahakam_2",
        count: 1,
        abilities: [],
    },
    {
        name: "Mahakaman Defender",
        id: "118",
        deck: "scoiatael",
        row: "close",
        strength: 5,
        filename: "mahakam_3",
        count: 1,
        abilities: [],
    },
    {
        name: "Mahakaman Defender",
        id: "119",
        deck: "scoiatael",
        row: "close",
        strength: 5,
        filename: "mahakam_4",
        count: 1,
        abilities: [],
    },
    {
        name: "Milva",
        id: "101",
        deck: "scoiatael",
        row: "ranged",
        strength: 10,
        filename: "milva",
        count: 1,
        abilities: [
            "morale",
        ],
    },
    {
        name: "Riordain",
        id: "130",
        deck: "scoiatael",
        row: "ranged",
        strength: 1,
        filename: "riordain",
        count: 1,
        abilities: [],
    },
    {
        name: "Saesenthessis",
        id: "18",
        deck: "scoiatael",
        row: "ranged",
        strength: 10,
        filename: "saskia",
        count: 1,
        abilities: [
            "hero",
        ],
    },
    {
        name: "Toruviel",
        id: "126",
        deck: "scoiatael",
        row: "ranged",
        strength: 2,
        filename: "toruviel",
        count: 1,
        abilities: [],
    },
    {
        name: "Vrihedd Brigade Recruit",
        id: "120",
        deck: "scoiatael",
        row: "ranged",
        strength: 4,
        filename: "vrihedd_cadet",
        count: 1,
        abilities: [],
    },
    {
        name: "Vrihedd Brigade Veteran",
        id: "113",
        deck: "scoiatael",
        row: "agile",
        strength: 5,
        filename: "vrihedd_brigade",
        count: 1,
        abilities: [],
    },
    {
        name: "Vrihedd Brigade Veteran",
        id: "114",
        deck: "scoiatael",
        row: "agile",
        strength: 5,
        filename: "vrihedd_brigade_1",
        count: 1,
        abilities: [],
    },
    {
        name: "Yaevinn",
        id: "105",
        deck: "scoiatael",
        row: "agile",
        strength: 6,
        filename: "yaevinn",
        count: 1,
        abilities: [],
    },
    {
        name: "Berserker",
        id: "",
        deck: "skellige",
        row: "close",
        strength: 4,
        filename: "berserker",
        count: 1,
        abilities: [
            "berserker",
        ],
    },
    {
        name: "Birna Bran",
        id: "",
        deck: "skellige",
        row: "close",
        strength: 2,
        filename: "birna",
        count: 1,
        abilities: [
            "medic",
        ],
    },
    {
        name: "Blueboy Lugos",
        id: "",
        deck: "skellige",
        row: "close",
        strength: 6,
        filename: "blueboy",
        count: 1,
        abilities: [],
    },
    {
        name: "Cerys",
        id: "",
        deck: "skellige",
        row: "close",
        strength: 10,
        filename: "cerys",
        count: 1,
        abilities: [
            "hero",
            "muster",
        ],
    },
    {
        name: "Clan Brokva Archer",
        id: "",
        deck: "skellige",
        row: "ranged",
        strength: 6,
        filename: "brokva_archer",
        count: 2,
        abilities: [],
    },
    {
        name: "Clan Dimun Pirate",
        id: "",
        deck: "skellige",
        row: "ranged",
        strength: 6,
        filename: "dimun_pirate",
        count: 1,
        abilities: [
            "scorch",
        ],
    },
    {
        name: "Cerys - Clan Drummond Shield Maiden",
        id: "",
        deck: "skellige",
        row: "close",
        strength: 4,
        filename: "shield_maiden",
        count: 1,
        abilities: [
            "bond",
        ],
    },
    {
        name: "Cerys - Clan Drummond Shield Maiden",
        id: "",
        deck: "skellige",
        row: "close",
        strength: 4,
        filename: "shield_maiden_1",
        count: 1,
        abilities: [
            "bond",
        ],
    },
    {
        name: "Cerys - Clan Drummond Shield Maiden",
        id: "",
        deck: "skellige",
        row: "close",
        strength: 4,
        filename: "shield_maiden_2",
        count: 1,
        abilities: [
            "bond",
        ],
    },
    {
        name: "Clan Heymaey Skald",
        id: "",
        deck: "skellige",
        row: "close",
        strength: 4,
        filename: "heymaey",
        count: 1,
        abilities: [],
    },
    {
        name: "Clan Tordarroch Armorsmith",
        id: "",
        deck: "skellige",
        row: "close",
        strength: 4,
        filename: "tordarroch",
        count: 1,
        abilities: [],
    },
    {
        name: "Clan an Craite Warrior",
        id: "",
        deck: "skellige",
        row: "close",
        strength: 6,
        filename: "craite_warrior",
        count: 3,
        abilities: [
            "bond",
        ],
    },
    {
        name: "Donar an Hindar",
        id: "",
        deck: "skellige",
        row: "close",
        strength: 4,
        filename: "donar",
        count: 1,
        abilities: [],
    },
    {
        name: "Draig Bon-Dhu",
        id: "",
        deck: "skellige",
        row: "siege",
        strength: 2,
        filename: "draig",
        count: 1,
        abilities: [
            "horn",
        ],
    },
    {
        name: "Ermion",
        id: "",
        deck: "skellige",
        row: "ranged",
        strength: 8,
        filename: "ermion",
        count: 1,
        abilities: [
            "hero",
            "mardroeme",
        ],
    },
    {
        name: "Hemdall",
        id: "",
        deck: "skellige",
        row: "close",
        strength: 11,
        filename: "hemdall",
        count: 0,
        abilities: [
            "hero",
        ],
    },
    {
        name: "Hjalmar",
        id: "",
        deck: "skellige",
        row: "ranged",
        strength: 10,
        filename: "hjalmar",
        count: 1,
        abilities: [
            "hero",
        ],
    },
    {
        name: "Holger Blackhand",
        id: "",
        deck: "skellige",
        row: "siege",
        strength: 4,
        filename: "holger",
        count: 1,
        abilities: [],
    },
    {
        name: "Kambi",
        id: "",
        deck: "skellige",
        row: "close",
        strength: 0,
        filename: "kambi",
        count: 1,
        abilities: [
            "avenger_kambi",
        ],
    },
    {
        name: "Light Longship",
        id: "",
        deck: "skellige",
        row: "ranged",
        strength: 4,
        filename: "light_longship",
        count: 3,
        abilities: [
            "muster",
        ],
    },
    {
        name: "Madman Lugos",
        id: "",
        deck: "skellige",
        row: "close",
        strength: 6,
        filename: "madmad_lugos",
        count: 1,
        abilities: [],
    },
    {
        name: "Mardroeme",
        id: "",
        deck: "special",
        row: "",
        strength: 0,
        filename: "mardroeme",
        count: 3,
        abilities: [
            "mardroeme",
        ],
    },
    {
        name: "Olaf",
        id: "",
        deck: "skellige",
        row: "agile",
        strength: 12,
        filename: "olaf",
        count: 1,
        abilities: [
            "morale",
        ],
    },
    {
        name: "Skellige Storm",
        id: "",
        deck: "weather",
        row: "",
        strength: 0,
        filename: "storm",
        count: 3,
        abilities: [
            "rain",
            "fog",
        ],
    },
    {
        name: "Svanrige",
        id: "",
        deck: "skellige",
        row: "close",
        strength: 4,
        filename: "svanrige",
        count: 1,
        abilities: [],
    },
    {
        name: "Transformed Vildkaarl",
        id: "",
        deck: "skellige",
        row: "close",
        strength: 14,
        filename: "vildkaarl",
        count: 0,
        abilities: [
            "morale",
        ],
    },
    {
        name: "Transformed Young Vildkaarl",
        id: "",
        deck: "skellige",
        row: "ranged",
        strength: 8,
        filename: "young_vildkaarl",
        count: 0,
        abilities: [
            "bond",
        ],
    },
    {
        name: "Udalryk",
        id: "",
        deck: "skellige",
        row: "close",
        strength: 4,
        filename: "udalryk",
        count: 1,
        abilities: [],
    },
    {
        name: "War Longship",
        id: "",
        deck: "skellige",
        row: "siege",
        strength: 6,
        filename: "war_longship",
        count: 2,
        abilities: [
            "bond",
        ],
    },
    {
        name: "Young Berserker",
        id: "",
        deck: "skellige",
        row: "ranged",
        strength: 2,
        filename: "young_berserker",
        count: 3,
        abilities: [
            "berserker",
        ],
    },
    {
        name: "Crach an Craite",
        id: "",
        deck: "skellige",
        row: "leader",
        strength: 0,
        filename: "crach_an_craite",
        count: 0,
        abilities: [
            "crach_an_craite",
        ],
    },
    {
        name: "King Bran",
        id: "",
        deck: "skellige",
        row: "leader",
        strength: 0,
        filename: "king_bran",
        count: 0,
        abilities: [
            "king_bran",
        ],
    },
    {
        name: "Schirru",
        id: "",
        deck: "scoiatael",
        row: "siege",
        strength: 8,
        filename: "schirru",
        count: 1,
        abilities: [
            "scorch_s",
        ],
    },
];

export default cards;
