import type {CardData, SerializedCard} from "./types/card.js";

export const minUnitAmountPerDeck = 22;

export const maxSpecialAmountPerDeck = 10;

export const serialize = ({filename}: CardData): SerializedCard => filename;

export const deserialize = (filename: SerializedCard) => {
    const card = cards[filename];
    if (!card) {
        throw new Error(`card not found ${filename}`);
    }

    return card
};

type CardWithAmount = CardData & {amount: number};
export const stackCards = (cards: CardData[]): Map<SerializedCard, CardWithAmount> => cards.reduce((acc, card) => {
    const previousCard = acc.get(card.filename);
    if (previousCard) {
        previousCard.amount += 1;
    } else {
        acc.set(card.filename, {...card, amount: 1});
    }

    return acc;
}, new Map());

const cards: Record<SerializedCard, CardData> = {
    "mysterious_elf": {
        name: "Mysterious Elf",
        strength: 0,
        filename: "mysterious_elf",
        maxPerDeck: 1,
        abilities: ["hero", "spy"],
        faction: "neutral",
        type: "unit",
        rows: ["close"],
    },
    "decoy": {
        name: "Decoy",
        strength: 0,
        filename: "decoy",
        maxPerDeck: 3,
        abilities: ["decoy"],
        faction: "neutral",
        type: "unit",
        rows: ["close", "ranged", "siege"],
    },
    "frost": {
        name: "Biting Frost",
        filename: "frost",
        maxPerDeck: 3,
        abilities: ["frost"],
        faction: "neutral",
        type: "weather",
    },
    "ciri": {
        name: "Cirilla Fiona Elen Riannon",
        strength: 15,
        filename: "ciri",
        maxPerDeck: 1,
        abilities: ["hero"],
        faction: "neutral",
        type: "unit",
        rows: ["close"],
    },
    "clear": {
        name: "Clear Weather",
        filename: "clear",
        maxPerDeck: 2,
        abilities: ["clear"],
        faction: "neutral",
        type: "weather",
    },
    "horn": {
        name: "Commander's Horn",
        filename: "horn",
        maxPerDeck: 3,
        abilities: ["horn"],
        faction: "neutral",
        type: "special",
        rows: ["close", "ranged", "siege"],
    },
    "dandelion": {
        name: "Dandelion",
        strength: 2,
        filename: "dandelion",
        maxPerDeck: 1,
        abilities: ["horn"],
        faction: "neutral",
        type: "unit",
        rows: ["close"],
    },
    "emiel": {
        name: "Emiel Regis Rohellec Terzieff",
        strength: 5,
        filename: "emiel",
        maxPerDeck: 1,
        abilities: [],
        faction: "neutral",
        type: "unit",
        rows: ["close"],
    },
    "geralt": {
        name: "Geralt of Rivia",
        strength: 15,
        filename: "geralt",
        maxPerDeck: 1,
        abilities: ["hero"],
        faction: "neutral",
        type: "unit",
        rows: ["close"],
    },
    "fog": {
        name: "Impenetrable Fog",
        filename: "fog",
        maxPerDeck: 3,
        abilities: ["fog"],
        faction: "neutral",
        type: "weather",
    },
    "scorch": {
        name: "Scorch",
        filename: "scorch",
        maxPerDeck: 3,
        abilities: ["scorch"],
        faction: "neutral",
        type: "weather",
    },
    "rain": {
        name: "Torrential Rain",
        filename: "rain",
        maxPerDeck: 2,
        abilities: ["rain"],
        faction: "neutral",
        type: "weather",
    },
    "triss": {
        name: "Triss Merigold",
        strength: 7,
        filename: "triss",
        maxPerDeck: 1,
        abilities: ["hero"],
        faction: "neutral",
        type: "unit",
        rows: ["close"],
    },
    "vesemir": {
        name: "Vesemir",
        strength: 6,
        filename: "vesemir",
        maxPerDeck: 1,
        abilities: [],
        faction: "neutral",
        type: "unit",
        rows: ["close"],
    },
    "villen": {
        name: "Villentretenmerth",
        strength: 7,
        filename: "villen",
        maxPerDeck: 1,
        abilities: ["scorch_c"],
        faction: "neutral",
        type: "unit",
        rows: ["close"],
    },
    "yennefer": {
        name: "Yennefer of Vengerberg",
        strength: 7,
        filename: "yennefer",
        maxPerDeck: 1,
        abilities: ["hero", "medic"],
        faction: "neutral",
        type: "unit",
        rows: ["ranged"],
    },
    "zoltan": {
        name: "Zoltan Chivay",
        strength: 5,
        filename: "zoltan",
        maxPerDeck: 1,
        abilities: [],
        faction: "neutral",
        type: "unit",
        rows: ["close"],
    },
    "olgierd": {
        name: "Olgierd von Everec",
        strength: 6,
        filename: "olgierd",
        maxPerDeck: 1,
        abilities: ["agile", "morale"],
        faction: "neutral",
        type: "unit",
        rows: ["close", "ranged"],
    },
    "gaunter_odimm": {
        name: "Gaunter O'Dimm",
        strength: 2,
        filename: "gaunter_odimm",
        maxPerDeck: 1,
        abilities: ["muster"],
        faction: "neutral",
        type: "unit",
        rows: ["siege"],
    },
    "gaunter_odimm_darkness": {
        name: "Gaunter O'Dimm - Darkness",
        strength: 4,
        filename: "gaunter_odimm_darkness",
        maxPerDeck: 3,
        abilities: ["muster"],
        faction: "neutral",
        type: "unit",
        rows: ["ranged"],
    },
    "cow": {
        name: "Cow",
        strength: 0,
        filename: "cow",
        maxPerDeck: 1,
        abilities: ["avenger"],
        faction: "neutral",
        type: "unit",
        rows: ["ranged"],
    },
    "chort": {
        name: "Bovine Defense Force",
        strength: 8,
        filename: "chort",
        maxPerDeck: 0,
        abilities: [],
        faction: "neutral",
        type: "unit",
        rows: ["close"],
    },
    "foltest_silver": {
        name: "Foltest - King of Temeria",
        filename: "foltest_silver",
        maxPerDeck: 1,
        abilities: ["foltest_king"],
        faction: "realms",
        type: "leader",
    },
    "foltest_gold": {
        name: "Foltest - Lord Commander of the North",
        filename: "foltest_gold",
        maxPerDeck: 1,
        abilities: ["foltest_lord"],
        faction: "realms",
        type: "leader",
    },
    "foltest_copper": {
        name: "Foltest - The Siegemaster",
        filename: "foltest_copper",
        maxPerDeck: 1,
        abilities: ["foltest_siegemaster"],
        faction: "realms",
        type: "leader",
    },
    "foltest_bronze": {
        name: "Foltest - The Steel-Forged",
        filename: "foltest_bronze",
        maxPerDeck: 1,
        abilities: ["foltest_steelforged"],
        faction: "realms",
        type: "leader",
    },
    "foltest_son_of_medell": {
        name: "Foltest - Son of Medell",
        filename: "foltest_son_of_medell",
        maxPerDeck: 1,
        abilities: ["foltest_son"],
        faction: "realms",
        type: "leader",
    },
    "ballista": {
        name: "Ballista",
        strength: 6,
        filename: "ballista",
        maxPerDeck: 1,
        abilities: [],
        faction: "realms",
        type: "unit",
        rows: ["siege"],
    },
    "blue_stripes": {
        name: "Blue Stripes Commando",
        strength: 4,
        filename: "blue_stripes",
        maxPerDeck: 3,
        abilities: ["bond"],
        faction: "realms",
        type: "unit",
        rows: ["close"],
    },
    "catapult_1": {
        name: "Catapult",
        strength: 8,
        filename: "catapult_1",
        maxPerDeck: 2,
        abilities: ["bond"],
        faction: "realms",
        type: "unit",
        rows: ["siege"],
    },
    "crinfrid": {
        name: "Crinfrid Reavers Dragon Hunter",
        strength: 5,
        filename: "crinfrid",
        maxPerDeck: 3,
        abilities: ["bond"],
        faction: "realms",
        type: "unit",
        rows: ["ranged"],
    },
    "dethmold": {
        name: "Dethmold",
        strength: 6,
        filename: "dethmold",
        maxPerDeck: 1,
        abilities: [],
        faction: "realms",
        type: "unit",
        rows: ["ranged"],
    },
    "banner_nurse": {
        name: "Dun Banner Medic",
        strength: 5,
        filename: "banner_nurse",
        maxPerDeck: 1,
        abilities: ["medic"],
        faction: "realms",
        type: "unit",
        rows: ["siege"],
    },
    "esterad": {
        name: "Esterad Thyssen",
        strength: 10,
        filename: "esterad",
        maxPerDeck: 1,
        abilities: ["hero"],
        faction: "realms",
        type: "unit",
        rows: ["close"],
    },
    "natalis": {
        name: "John Natalis",
        strength: 10,
        filename: "natalis",
        maxPerDeck: 1,
        abilities: ["hero"],
        faction: "realms",
        type: "unit",
        rows: ["close"],
    },
    "kaedwen_siege": {
        name: "Kaedweni Siege Expert",
        strength: 1,
        filename: "kaedwen_siege",
        maxPerDeck: 1,
        abilities: ["morale"],
        faction: "realms",
        type: "unit",
        rows: ["siege"],
    },
    "kaedwen_siege_1": {
        name: "Kaedweni Siege Expert",
        strength: 1,
        filename: "kaedwen_siege_1",
        maxPerDeck: 1,
        abilities: ["morale"],
        faction: "realms",
        type: "unit",
        rows: ["siege"],
    },
    "kaedwen_siege_2": {
        name: "Kaedweni Siege Expert",
        strength: 1,
        filename: "kaedwen_siege_2",
        maxPerDeck: 1,
        abilities: ["morale"],
        faction: "realms",
        type: "unit",
        rows: ["siege"],
    },
    "keira": {
        name: "Keira Metz",
        strength: 5,
        filename: "keira",
        maxPerDeck: 1,
        abilities: [],
        faction: "realms",
        type: "unit",
        rows: ["ranged"],
    },
    "philippa": {
        name: "Philippa Eilhart",
        strength: 10,
        filename: "philippa",
        maxPerDeck: 1,
        abilities: ["hero"],
        faction: "realms",
        type: "unit",
        rows: ["ranged"],
    },
    "poor_infantry": {
        name: "Poor Fucking Infantry",
        strength: 1,
        filename: "poor_infantry",
        maxPerDeck: 4,
        abilities: ["bond"],
        faction: "realms",
        type: "unit",
        rows: ["close"],
    },
    "stennis": {
        name: "Prince Stennis",
        strength: 5,
        filename: "stennis",
        maxPerDeck: 1,
        abilities: ["spy"],
        faction: "realms",
        type: "unit",
        rows: ["close"],
    },
    "redania": {
        name: "Redanian Foot Soldier",
        strength: 1,
        filename: "redania",
        maxPerDeck: 1,
        abilities: [],
        faction: "realms",
        type: "unit",
        rows: ["close"],
    },
    "redania_1": {
        name: "Redanian Foot Soldier",
        strength: 1,
        filename: "redania_1",
        maxPerDeck: 1,
        abilities: [],
        faction: "realms",
        type: "unit",
        rows: ["close"],
    },
    "sheldon": {
        name: "Sheldon Skaggs",
        strength: 4,
        filename: "sheldon",
        maxPerDeck: 1,
        abilities: [],
        faction: "realms",
        type: "unit",
        rows: ["ranged"],
    },
    "siege_tower": {
        name: "Siege Tower",
        strength: 6,
        filename: "siege_tower",
        maxPerDeck: 1,
        abilities: [],
        faction: "realms",
        type: "unit",
        rows: ["siege"],
    },
    "siegfried": {
        name: "Siegfried of Denesle",
        strength: 5,
        filename: "siegfried",
        maxPerDeck: 1,
        abilities: [],
        faction: "realms",
        type: "unit",
        rows: ["close"],
    },
    "dijkstra": {
        name: "Sigismund Dijkstra",
        strength: 4,
        filename: "dijkstra",
        maxPerDeck: 1,
        abilities: ["spy"],
        faction: "realms",
        type: "unit",
        rows: ["close"],
    },
    "sheala": {
        name: "Síle de Tansarville",
        strength: 5,
        filename: "sheala",
        maxPerDeck: 1,
        abilities: [],
        faction: "realms",
        type: "unit",
        rows: ["ranged"],
    },
    "thaler": {
        name: "Thaler",
        strength: 1,
        filename: "thaler",
        maxPerDeck: 1,
        abilities: ["spy"],
        faction: "realms",
        type: "unit",
        rows: ["siege"],
    },
    "sabrina": {
        name: "Sabrina Glevissig",
        strength: 4,
        filename: "sabrina",
        maxPerDeck: 1,
        abilities: [],
        faction: "realms",
        type: "unit",
        rows: ["ranged"],
    },
    "vernon": {
        name: "Vernon Roche",
        strength: 10,
        filename: "vernon",
        maxPerDeck: 1,
        abilities: ["hero"],
        faction: "realms",
        type: "unit",
        rows: ["close"],
    },
    "ves": {
        name: "Ves",
        strength: 5,
        filename: "ves",
        maxPerDeck: 1,
        abilities: [],
        faction: "realms",
        type: "unit",
        rows: ["close"],
    },
    "yarpen": {
        name: "Yarpen Zigrin",
        strength: 2,
        filename: "yarpen",
        maxPerDeck: 1,
        abilities: [],
        faction: "realms",
        type: "unit",
        rows: ["close"],
    },
    "trebuchet": {
        name: "Trebuchet",
        strength: 6,
        filename: "trebuchet",
        maxPerDeck: 1,
        abilities: [],
        faction: "realms",
        type: "unit",
        rows: ["siege"],
    },
    "trebuchet_1": {
        name: "Trebuchet",
        strength: 6,
        filename: "trebuchet_1",
        maxPerDeck: 1,
        abilities: [],
        faction: "realms",
        type: "unit",
        rows: ["siege"],
    },
    "emhyr_silver": {
        name: "Emhyr var Emreis - His Imperial Majesty",
        filename: "emhyr_silver",
        maxPerDeck: 1,
        abilities: ["emhyr_imperial"],
        faction: "nilfgaard",
        type: "leader",
    },
    "emhyr_copper": {
        name: "Emhyr var Emreis - Emperor of Nilfgaard",
        filename: "emhyr_copper",
        maxPerDeck: 1,
        abilities: ["emhyr_emperor"],
        faction: "nilfgaard",
        type: "leader",
    },
    "emhyr_bronze": {
        name: "Emhyr var Emreis - the White Flame",
        filename: "emhyr_bronze",
        maxPerDeck: 1,
        abilities: ["emhyr_whiteflame"],
        faction: "nilfgaard",
        type: "leader",
    },
    "emhyr_gold": {
        name: "Emhyr var Emreis - The Relentless",
        filename: "emhyr_gold",
        maxPerDeck: 1,
        abilities: ["emhyr_relentless"],
        faction: "nilfgaard",
        type: "leader",
    },
    "emhyr_invader_of_the_north": {
        name: "Emhyr var Emreis - Invader of the North",
        filename: "emhyr_invader_of_the_north",
        maxPerDeck: 1,
        abilities: ["emhyr_invader"],
        faction: "nilfgaard",
        type: "leader",
    },
    "albrich": {
        name: "Albrich",
        strength: 2,
        filename: "albrich",
        maxPerDeck: 1,
        abilities: [],
        faction: "nilfgaard",
        type: "unit",
        rows: ["ranged"],
    },
    "assire": {
        name: "Assire var Anahid",
        strength: 6,
        filename: "assire",
        maxPerDeck: 1,
        abilities: [],
        faction: "nilfgaard",
        type: "unit",
        rows: ["ranged"],
    },
    "black_archer": {
        name: "Black Infantry Archer",
        strength: 10,
        filename: "black_archer",
        maxPerDeck: 1,
        abilities: [],
        faction: "nilfgaard",
        type: "unit",
        rows: ["ranged"],
    },
    "black_archer_1": {
        name: "Black Infantry Archer",
        strength: 10,
        filename: "black_archer_1",
        maxPerDeck: 1,
        abilities: [],
        faction: "nilfgaard",
        type: "unit",
        rows: ["ranged"],
    },
    "cahir": {
        name: "Cahir Mawr Dyffryn aep Ceallach",
        strength: 6,
        filename: "cahir",
        maxPerDeck: 1,
        abilities: [],
        faction: "nilfgaard",
        type: "unit",
        rows: ["close"],
    },
    "cynthia": {
        name: "Cynthia",
        strength: 4,
        filename: "cynthia",
        maxPerDeck: 1,
        abilities: [],
        faction: "nilfgaard",
        type: "unit",
        rows: ["ranged"],
    },
    "archer_support": {
        name: "Etolian Auxiliary Archers",
        strength: 1,
        filename: "archer_support",
        maxPerDeck: 1,
        abilities: ["medic"],
        faction: "nilfgaard",
        type: "unit",
        rows: ["ranged"],
    },
    "archer_support_1": {
        name: "Etolian Auxiliary Archers",
        strength: 1,
        filename: "archer_support_1",
        maxPerDeck: 1,
        abilities: ["medic"],
        faction: "nilfgaard",
        type: "unit",
        rows: ["ranged"],
    },
    "fringilla": {
        name: "Fringilla Vigo",
        strength: 6,
        filename: "fringilla",
        maxPerDeck: 1,
        abilities: [],
        faction: "nilfgaard",
        type: "unit",
        rows: ["ranged"],
    },
    "heavy_zerri": {
        name: "Heavy Zerrikanian Fire Scorpion",
        strength: 10,
        filename: "heavy_zerri",
        maxPerDeck: 1,
        abilities: [],
        faction: "nilfgaard",
        type: "unit",
        rows: ["siege"],
    },
    "imperal_brigade": {
        name: "Impera Brigade Guard",
        strength: 3,
        filename: "imperal_brigade",
        maxPerDeck: 4,
        abilities: ["bond"],
        faction: "nilfgaard",
        type: "unit",
        rows: ["close"],
    },
    "letho": {
        name: "Letho of Gulet",
        strength: 10,
        filename: "letho",
        maxPerDeck: 1,
        abilities: ["hero"],
        faction: "nilfgaard",
        type: "unit",
        rows: ["close"],
    },
    "menno": {
        name: "Menno Coehoorn",
        strength: 10,
        filename: "menno",
        maxPerDeck: 1,
        abilities: ["hero", "medic"],
        faction: "nilfgaard",
        type: "unit",
        rows: ["close"],
    },
    "morteisen": {
        name: "Morteisen",
        strength: 3,
        filename: "morteisen",
        maxPerDeck: 1,
        abilities: [],
        faction: "nilfgaard",
        type: "unit",
        rows: ["close"],
    },
    "moorvran": {
        name: "Morvran Voorhis",
        strength: 10,
        filename: "moorvran",
        maxPerDeck: 1,
        abilities: ["hero"],
        faction: "nilfgaard",
        type: "unit",
        rows: ["siege"],
    },
    "nauzicaa_2": {
        name: "Nausicaa Cavalry Rider",
        strength: 2,
        filename: "nauzicaa_2",
        maxPerDeck: 3,
        abilities: ["bond"],
        faction: "nilfgaard",
        type: "unit",
        rows: ["close"],
    },
    "puttkammer": {
        name: "Puttkammer",
        strength: 3,
        filename: "puttkammer",
        maxPerDeck: 1,
        abilities: [],
        faction: "nilfgaard",
        type: "unit",
        rows: ["ranged"],
    },
    "rainfarn": {
        name: "Rainfarn",
        strength: 4,
        filename: "rainfarn",
        maxPerDeck: 1,
        abilities: [],
        faction: "nilfgaard",
        type: "unit",
        rows: ["close"],
    },
    "renuald": {
        name: "Renuald aep Matsen",
        strength: 5,
        filename: "renuald",
        maxPerDeck: 1,
        abilities: [],
        faction: "nilfgaard",
        type: "unit",
        rows: ["ranged"],
    },
    "rotten": {
        name: "Rotten Mangonel",
        strength: 3,
        filename: "rotten",
        maxPerDeck: 1,
        abilities: [],
        faction: "nilfgaard",
        type: "unit",
        rows: ["siege"],
    },
    "shilard": {
        name: "Shilard Fitz-Oesterlen",
        strength: 7,
        filename: "shilard",
        maxPerDeck: 1,
        abilities: ["spy"],
        faction: "nilfgaard",
        type: "unit",
        rows: ["close"],
    },
    "siege_engineer": {
        name: "Siege Engineer",
        strength: 6,
        filename: "siege_engineer",
        maxPerDeck: 1,
        abilities: [],
        faction: "nilfgaard",
        type: "unit",
        rows: ["siege"],
    },
    "siege_support": {
        name: "Siege Technician",
        strength: 0,
        filename: "siege_support",
        maxPerDeck: 1,
        abilities: ["medic"],
        faction: "nilfgaard",
        type: "unit",
        rows: ["siege"],
    },
    "stefan": {
        name: "Stefan Skellen",
        strength: 9,
        filename: "stefan",
        maxPerDeck: 1,
        abilities: ["spy"],
        faction: "nilfgaard",
        type: "unit",
        rows: ["close"],
    },
    "sweers": {
        name: "Sweers",
        strength: 2,
        filename: "sweers",
        maxPerDeck: 1,
        abilities: [],
        faction: "nilfgaard",
        type: "unit",
        rows: ["ranged"],
    },
    "tibor": {
        name: "Tibor Eggebracht",
        strength: 10,
        filename: "tibor",
        maxPerDeck: 1,
        abilities: ["hero"],
        faction: "nilfgaard",
        type: "unit",
        rows: ["ranged"],
    },
    "vanhemar": {
        name: "Vanhemar",
        strength: 4,
        filename: "vanhemar",
        maxPerDeck: 1,
        abilities: [],
        faction: "nilfgaard",
        type: "unit",
        rows: ["ranged"],
    },
    "vattier": {
        name: "Vattier de Rideaux",
        strength: 4,
        filename: "vattier",
        maxPerDeck: 1,
        abilities: ["spy"],
        faction: "nilfgaard",
        type: "unit",
        rows: ["close"],
    },
    "vreemde": {
        name: "Vreemde",
        strength: 2,
        filename: "vreemde",
        maxPerDeck: 1,
        abilities: [],
        faction: "nilfgaard",
        type: "unit",
        rows: ["close"],
    },
    "young_emissary": {
        name: "Young Emissary",
        strength: 5,
        filename: "young_emissary",
        maxPerDeck: 1,
        abilities: ["bond"],
        faction: "nilfgaard",
        type: "unit",
        rows: ["close"],
    },
    "young_emissary_1": {
        name: "Young Emissary",
        strength: 5,
        filename: "young_emissary_1",
        maxPerDeck: 1,
        abilities: ["bond"],
        faction: "nilfgaard",
        type: "unit",
        rows: ["close"],
    },
    "zerri": {
        name: "Zerrikanian Fire Scorpion",
        strength: 5,
        filename: "zerri",
        maxPerDeck: 1,
        abilities: [],
        faction: "nilfgaard",
        type: "unit",
        rows: ["siege"],
    },
    "eredin_silver": {
        name: "Eredin - Commander of the Red Riders",
        filename: "eredin_silver",
        maxPerDeck: 1,
        abilities: ["eredin_commander"],
        faction: "monsters",
        type: "leader",
    },
    "eredin_bronze": {
        name: "Eredin - Bringer of Death",
        filename: "eredin_bronze",
        maxPerDeck: 1,
        abilities: ["eredin_bringer_of_death"],
        faction: "monsters",
        type: "leader",
    },
    "eredin_gold": {
        name: "Eredin - Destroyer of Worlds",
        filename: "eredin_gold",
        maxPerDeck: 1,
        abilities: ["eredin_destroyer"],
        faction: "monsters",
        type: "leader",
    },
    "eredin_copper": {
        name: "Eredin - King of the Wild Hunt",
        filename: "eredin_copper",
        maxPerDeck: 1,
        abilities: ["eredin_king"],
        faction: "monsters",
        type: "leader",
    },
    "eredin_the_treacherous": {
        name: "Eredin Bréacc Glas - The Treacherous",
        filename: "eredin_the_treacherous",
        maxPerDeck: 1,
        abilities: ["eredin_treacherous"],
        faction: "monsters",
        type: "leader",
    },
    "arachas": {
        name: "Arachas ",
        strength: 4,
        filename: "arachas",
        maxPerDeck: 1,
        abilities: ["muster"],
        faction: "monsters",
        type: "unit",
        rows: ["close"],
    },
    "arachas_1": {
        name: "Arachas ",
        strength: 4,
        filename: "arachas_1",
        maxPerDeck: 1,
        abilities: ["muster"],
        faction: "monsters",
        type: "unit",
        rows: ["close"],
    },
    "arachas_2": {
        name: "Arachas ",
        strength: 4,
        filename: "arachas_2",
        maxPerDeck: 1,
        abilities: ["muster"],
        faction: "monsters",
        type: "unit",
        rows: ["close"],
    },
    "arachas_behemoth": {
        name: "Arachas- Behemoth",
        strength: 6,
        filename: "arachas_behemoth",
        maxPerDeck: 1,
        abilities: ["muster"],
        faction: "monsters",
        type: "unit",
        rows: ["siege"],
    },
    "poroniec": {
        name: "Botchling",
        strength: 4,
        filename: "poroniec",
        maxPerDeck: 1,
        abilities: [],
        faction: "monsters",
        type: "unit",
        rows: ["close"],
    },
    "celaeno_harpy": {
        name: "Celaeno Harpy",
        strength: 2,
        filename: "celaeno_harpy",
        maxPerDeck: 1,
        abilities: ["agile"],
        faction: "monsters",
        type: "unit",
        rows: ["close", "ranged"],
    },
    "cockatrice": {
        name: "Cockatrice",
        strength: 2,
        filename: "cockatrice",
        maxPerDeck: 1,
        abilities: [],
        faction: "monsters",
        type: "unit",
        rows: ["ranged"],
    },
    "witch_velen": {
        name: "Crone - Brewess",
        strength: 6,
        filename: "witch_velen",
        maxPerDeck: 1,
        abilities: ["muster"],
        faction: "monsters",
        type: "unit",
        rows: ["close"],
    },
    "witch_velen_1": {
        name: "Crone - Weavess",
        strength: 6,
        filename: "witch_velen_1",
        maxPerDeck: 1,
        abilities: ["muster"],
        faction: "monsters",
        type: "unit",
        rows: ["close"],
    },
    "witch_velen_2": {
        name: "Crone - Whispess",
        strength: 6,
        filename: "witch_velen_2",
        maxPerDeck: 1,
        abilities: ["muster"],
        faction: "monsters",
        type: "unit",
        rows: ["close"],
    },
    "draug": {
        name: "Draug",
        strength: 10,
        filename: "draug",
        maxPerDeck: 1,
        abilities: ["hero"],
        faction: "monsters",
        type: "unit",
        rows: ["close"],
    },
    "earth_elemental": {
        name: "Earth Elemental",
        strength: 6,
        filename: "earth_elemental",
        maxPerDeck: 1,
        abilities: [],
        faction: "monsters",
        type: "unit",
        rows: ["siege"],
    },
    "endrega": {
        name: "Endrega",
        strength: 2,
        filename: "endrega",
        maxPerDeck: 1,
        abilities: [],
        faction: "monsters",
        type: "unit",
        rows: ["ranged"],
    },
    "fiend": {
        name: "Fiend",
        strength: 6,
        filename: "fiend",
        maxPerDeck: 1,
        abilities: [],
        faction: "monsters",
        type: "unit",
        rows: ["close"],
    },
    "fire_elemental": {
        name: "Fire Elemental",
        strength: 6,
        filename: "fire_elemental",
        maxPerDeck: 1,
        abilities: [],
        faction: "monsters",
        type: "unit",
        rows: ["siege"],
    },
    "fogling": {
        name: "Foglet",
        strength: 2,
        filename: "fogling",
        maxPerDeck: 1,
        abilities: [],
        faction: "monsters",
        type: "unit",
        rows: ["close"],
    },
    "forktail": {
        name: "Forktail",
        strength: 5,
        filename: "forktail",
        maxPerDeck: 1,
        abilities: [],
        faction: "monsters",
        type: "unit",
        rows: ["close"],
    },
    "frightener": {
        name: "Frightener",
        strength: 5,
        filename: "frightener",
        maxPerDeck: 1,
        abilities: [],
        faction: "monsters",
        type: "unit",
        rows: ["close"],
    },
    "gargoyle": {
        name: "Gargoyle",
        strength: 2,
        filename: "gargoyle",
        maxPerDeck: 1,
        abilities: [],
        faction: "monsters",
        type: "unit",
        rows: ["ranged"],
    },
    "ghoul": {
        name: "Ghoul",
        strength: 1,
        filename: "ghoul",
        maxPerDeck: 1,
        abilities: ["muster"],
        faction: "monsters",
        type: "unit",
        rows: ["close"],
    },
    "ghoul_1": {
        name: "Ghoul",
        strength: 1,
        filename: "ghoul_1",
        maxPerDeck: 1,
        abilities: ["muster"],
        faction: "monsters",
        type: "unit",
        rows: ["close"],
    },
    "ghoul_2": {
        name: "Ghoul",
        strength: 1,
        filename: "ghoul_2",
        maxPerDeck: 1,
        abilities: ["muster"],
        faction: "monsters",
        type: "unit",
        rows: ["close"],
    },
    "gravehag": {
        name: "Grave Hag",
        strength: 5,
        filename: "gravehag",
        maxPerDeck: 1,
        abilities: [],
        faction: "monsters",
        type: "unit",
        rows: ["ranged"],
    },
    "gryffin": {
        name: "Griffin",
        strength: 5,
        filename: "gryffin",
        maxPerDeck: 1,
        abilities: [],
        faction: "monsters",
        type: "unit",
        rows: ["close"],
    },
    "harpy": {
        name: "Harpy",
        strength: 2,
        filename: "harpy",
        maxPerDeck: 1,
        abilities: ["agile"],
        faction: "monsters",
        type: "unit",
        rows: ["close", "ranged"],
    },
    "frost_giant": {
        name: "Ice Giant",
        strength: 5,
        filename: "frost_giant",
        maxPerDeck: 1,
        abilities: [],
        faction: "monsters",
        type: "unit",
        rows: ["siege"],
    },
    "imlerith": {
        name: "Imlerith",
        strength: 10,
        filename: "imlerith",
        maxPerDeck: 1,
        abilities: ["hero"],
        faction: "monsters",
        type: "unit",
        rows: ["close"],
    },
    "kayran": {
        name: "Kayran",
        strength: 8,
        filename: "kayran",
        maxPerDeck: 1,
        abilities: ["hero", "agile", "morale"],
        faction: "monsters",
        type: "unit",
        rows: ["close", "ranged"],
    },
    "leshen": {
        name: "Leshen",
        strength: 10,
        filename: "leshen",
        maxPerDeck: 1,
        abilities: ["hero"],
        faction: "monsters",
        type: "unit",
        rows: ["ranged"],
    },
    "nekker": {
        name: "Nekker",
        strength: 2,
        filename: "nekker",
        maxPerDeck: 1,
        abilities: ["muster"],
        faction: "monsters",
        type: "unit",
        rows: ["close"],
    },
    "nekker_1": {
        name: "Nekker",
        strength: 2,
        filename: "nekker_1",
        maxPerDeck: 1,
        abilities: ["muster"],
        faction: "monsters",
        type: "unit",
        rows: ["close"],
    },
    "nekker_2": {
        name: "Nekker",
        strength: 2,
        filename: "nekker_2",
        maxPerDeck: 1,
        abilities: ["muster"],
        faction: "monsters",
        type: "unit",
        rows: ["close"],
    },
    "mighty_maiden": {
        name: "Plague Maiden",
        strength: 5,
        filename: "mighty_maiden",
        maxPerDeck: 1,
        abilities: [],
        faction: "monsters",
        type: "unit",
        rows: ["close"],
    },
    "bruxa": {
        name: "Vampire - Bruxa",
        strength: 4,
        filename: "bruxa",
        maxPerDeck: 1,
        abilities: ["muster"],
        faction: "monsters",
        type: "unit",
        rows: ["close"],
    },
    "ekkima": {
        name: "Vampire - Ekimmara",
        strength: 4,
        filename: "ekkima",
        maxPerDeck: 1,
        abilities: ["muster"],
        faction: "monsters",
        type: "unit",
        rows: ["close"],
    },
    "fleder": {
        name: "Vampire - Fleder",
        strength: 4,
        filename: "fleder",
        maxPerDeck: 1,
        abilities: ["muster"],
        faction: "monsters",
        type: "unit",
        rows: ["close"],
    },
    "garkain": {
        name: "Vampire - Garkain",
        strength: 4,
        filename: "garkain",
        maxPerDeck: 1,
        abilities: ["muster"],
        faction: "monsters",
        type: "unit",
        rows: ["close"],
    },
    "katakan": {
        name: "Vampire - Katakan",
        strength: 5,
        filename: "katakan",
        maxPerDeck: 1,
        abilities: ["muster"],
        faction: "monsters",
        type: "unit",
        rows: ["close"],
    },
    "werewolf": {
        name: "Werewolf",
        strength: 5,
        filename: "werewolf",
        maxPerDeck: 1,
        abilities: [],
        faction: "monsters",
        type: "unit",
        rows: ["close"],
    },
    "wyvern": {
        name: "Wyvern",
        strength: 2,
        filename: "wyvern",
        maxPerDeck: 1,
        abilities: [],
        faction: "monsters",
        type: "unit",
        rows: ["ranged"],
    },
    "toad": {
        name: "Toad",
        strength: 7,
        filename: "toad",
        maxPerDeck: 1,
        abilities: ["scorch_r"],
        faction: "monsters",
        type: "unit",
        rows: ["ranged"],
    },
    "francesca_silver": {
        name: "Francesca Findabair - Queen of Dol Blathanna",
        filename: "francesca_silver",
        maxPerDeck: 1,
        abilities: ["francesca_queen"],
        faction: "scoiatael",
        type: "leader",
    },
    "francesca_gold": {
        name: "Francesca Findabair - the Beautiful",
        filename: "francesca_gold",
        maxPerDeck: 1,
        abilities: ["francesca_beautiful"],
        faction: "scoiatael",
        type: "leader",
    },
    "francesca_copper": {
        name: "Francesca Findabair - Daisy of the Valley",
        filename: "francesca_copper",
        maxPerDeck: 1,
        abilities: ["francesca_daisy"],
        faction: "scoiatael",
        type: "leader",
    },
    "francesca_bronze": {
        name: "Francesca Findabair - Pureblood Elf",
        filename: "francesca_bronze",
        maxPerDeck: 1,
        abilities: ["francesca_pureblood"],
        faction: "scoiatael",
        type: "leader",
    },
    "francesca_hope_of_the_aen_seidhe": {
        name: "Francesca Findabair - Hope of the Aen Seidhe",
        filename: "francesca_hope_of_the_aen_seidhe",
        maxPerDeck: 1,
        abilities: ["francesca_hope"],
        faction: "scoiatael",
        type: "leader",
    },
    "ciaran": {
        name: "Ciaran aep Easnillien",
        strength: 3,
        filename: "ciaran",
        maxPerDeck: 1,
        abilities: ["agile"],
        faction: "scoiatael",
        type: "unit",
        rows: ["close", "ranged"],
    },
    "barclay": {
        name: "Barclay Els",
        strength: 6,
        filename: "barclay",
        maxPerDeck: 1,
        abilities: ["agile"],
        faction: "scoiatael",
        type: "unit",
        rows: ["close", "ranged"],
    },
    "dennis": {
        name: "Dennis Cranmer",
        strength: 6,
        filename: "dennis",
        maxPerDeck: 1,
        abilities: [],
        faction: "scoiatael",
        type: "unit",
        rows: ["close"],
    },
    "dol_archer": {
        name: "Dol Blathanna Archer",
        strength: 4,
        filename: "dol_archer",
        maxPerDeck: 1,
        abilities: [],
        faction: "scoiatael",
        type: "unit",
        rows: ["ranged"],
    },
    "dol_infantry": {
        name: "Dol Blathanna Scout",
        strength: 6,
        filename: "dol_infantry",
        maxPerDeck: 1,
        abilities: ["agile"],
        faction: "scoiatael",
        type: "unit",
        rows: ["close", "ranged"],
    },
    "dol_infantry_1": {
        name: "Dol Blathanna Scout",
        strength: 6,
        filename: "dol_infantry_1",
        maxPerDeck: 1,
        abilities: ["agile"],
        faction: "scoiatael",
        type: "unit",
        rows: ["close", "ranged"],
    },
    "dol_infantry_2": {
        name: "Dol Blathanna Scout",
        strength: 6,
        filename: "dol_infantry_2",
        maxPerDeck: 1,
        abilities: ["agile"],
        faction: "scoiatael",
        type: "unit",
        rows: ["close", "ranged"],
    },
    "dwarf": {
        name: "Dwarven Skirmisher",
        strength: 3,
        filename: "dwarf",
        maxPerDeck: 1,
        abilities: ["muster"],
        faction: "scoiatael",
        type: "unit",
        rows: ["close"],
    },
    "dwarf_1": {
        name: "Dwarven Skirmisher",
        strength: 3,
        filename: "dwarf_1",
        maxPerDeck: 1,
        abilities: ["muster"],
        faction: "scoiatael",
        type: "unit",
        rows: ["close"],
    },
    "dwarf_2": {
        name: "Dwarven Skirmisher",
        strength: 3,
        filename: "dwarf_2",
        maxPerDeck: 1,
        abilities: ["muster"],
        faction: "scoiatael",
        type: "unit",
        rows: ["close"],
    },
    "eithne": {
        name: "Eithné",
        strength: 10,
        filename: "eithne",
        maxPerDeck: 1,
        abilities: ["hero"],
        faction: "scoiatael",
        type: "unit",
        rows: ["ranged"],
    },
    "elf_skirmisher": {
        name: "Elven Skirmisher",
        strength: 2,
        filename: "elf_skirmisher",
        maxPerDeck: 1,
        abilities: ["muster"],
        faction: "scoiatael",
        type: "unit",
        rows: ["ranged"],
    },
    "elf_skirmisher_1": {
        name: "Elven Skirmisher",
        strength: 2,
        filename: "elf_skirmisher_1",
        maxPerDeck: 1,
        abilities: ["muster"],
        faction: "scoiatael",
        type: "unit",
        rows: ["ranged"],
    },
    "elf_skirmisher_2": {
        name: "Elven Skirmisher",
        strength: 2,
        filename: "elf_skirmisher_2",
        maxPerDeck: 1,
        abilities: ["muster"],
        faction: "scoiatael",
        type: "unit",
        rows: ["ranged"],
    },
    "filavandrel": {
        name: "Filavandrel aen Fidhail",
        strength: 6,
        filename: "filavandrel",
        maxPerDeck: 1,
        abilities: ["agile"],
        faction: "scoiatael",
        type: "unit",
        rows: ["close", "ranged"],
    },
    "havekar_nurse": {
        name: "Havekar Healer",
        strength: 0,
        filename: "havekar_nurse",
        maxPerDeck: 1,
        abilities: ["medic"],
        faction: "scoiatael",
        type: "unit",
        rows: ["ranged"],
    },
    "havekar_nurse_1": {
        name: "Havekar Healer",
        strength: 0,
        filename: "havekar_nurse_1",
        maxPerDeck: 1,
        abilities: ["medic"],
        faction: "scoiatael",
        type: "unit",
        rows: ["ranged"],
    },
    "havekar_nurse_2": {
        name: "Havekar Healer",
        strength: 0,
        filename: "havekar_nurse_2",
        maxPerDeck: 1,
        abilities: ["medic"],
        faction: "scoiatael",
        type: "unit",
        rows: ["ranged"],
    },
    "havekar_support": {
        name: "Havekar Smuggler",
        strength: 5,
        filename: "havekar_support",
        maxPerDeck: 1,
        abilities: ["muster"],
        faction: "scoiatael",
        type: "unit",
        rows: ["close"],
    },
    "havekar_support_1": {
        name: "Havekar Smuggler",
        strength: 5,
        filename: "havekar_support_1",
        maxPerDeck: 1,
        abilities: ["muster"],
        faction: "scoiatael",
        type: "unit",
        rows: ["close"],
    },
    "havekar_support_2": {
        name: "Havekar Smuggler",
        strength: 5,
        filename: "havekar_support_2",
        maxPerDeck: 1,
        abilities: ["muster"],
        faction: "scoiatael",
        type: "unit",
        rows: ["close"],
    },
    "ida": {
        name: "Ida Emean aep Sivney",
        strength: 6,
        filename: "ida",
        maxPerDeck: 1,
        abilities: [],
        faction: "scoiatael",
        type: "unit",
        rows: ["ranged"],
    },
    "iorveth": {
        name: "Iorveth",
        strength: 10,
        filename: "iorveth",
        maxPerDeck: 1,
        abilities: ["hero"],
        faction: "scoiatael",
        type: "unit",
        rows: ["ranged"],
    },
    "isengrim": {
        name: "Isengrim Faoiltiarna",
        strength: 10,
        filename: "isengrim",
        maxPerDeck: 1,
        abilities: ["hero", "morale"],
        faction: "scoiatael",
        type: "unit",
        rows: ["close"],
    },
    "mahakam": {
        name: "Mahakaman Defender",
        strength: 5,
        filename: "mahakam",
        maxPerDeck: 1,
        abilities: [],
        faction: "scoiatael",
        type: "unit",
        rows: ["close"],
    },
    "mahakam_1": {
        name: "Mahakaman Defender",
        strength: 5,
        filename: "mahakam_1",
        maxPerDeck: 1,
        abilities: [],
        faction: "scoiatael",
        type: "unit",
        rows: ["close"],
    },
    "mahakam_2": {
        name: "Mahakaman Defender",
        strength: 5,
        filename: "mahakam_2",
        maxPerDeck: 1,
        abilities: [],
        faction: "scoiatael",
        type: "unit",
        rows: ["close"],
    },
    "mahakam_3": {
        name: "Mahakaman Defender",
        strength: 5,
        filename: "mahakam_3",
        maxPerDeck: 1,
        abilities: [],
        faction: "scoiatael",
        type: "unit",
        rows: ["close"],
    },
    "mahakam_4": {
        name: "Mahakaman Defender",
        strength: 5,
        filename: "mahakam_4",
        maxPerDeck: 1,
        abilities: [],
        faction: "scoiatael",
        type: "unit",
        rows: ["close"],
    },
    "milva": {
        name: "Milva",
        strength: 10,
        filename: "milva",
        maxPerDeck: 1,
        abilities: ["morale"],
        faction: "scoiatael",
        type: "unit",
        rows: ["ranged"],
    },
    "riordain": {
        name: "Riordain",
        strength: 1,
        filename: "riordain",
        maxPerDeck: 1,
        abilities: [],
        faction: "scoiatael",
        type: "unit",
        rows: ["ranged"],
    },
    "saskia": {
        name: "Saesenthessis",
        strength: 10,
        filename: "saskia",
        maxPerDeck: 1,
        abilities: ["hero"],
        faction: "scoiatael",
        type: "unit",
        rows: ["ranged"],
    },
    "toruviel": {
        name: "Toruviel",
        strength: 2,
        filename: "toruviel",
        maxPerDeck: 1,
        abilities: [],
        faction: "scoiatael",
        type: "unit",
        rows: ["ranged"],
    },
    "vrihedd_cadet": {
        name: "Vrihedd Brigade Recruit",
        strength: 4,
        filename: "vrihedd_cadet",
        maxPerDeck: 1,
        abilities: [],
        faction: "scoiatael",
        type: "unit",
        rows: ["ranged"],
    },
    "vrihedd_brigade": {
        name: "Vrihedd Brigade Veteran",
        strength: 5,
        filename: "vrihedd_brigade",
        maxPerDeck: 1,
        abilities: ["agile"],
        faction: "scoiatael",
        type: "unit",
        rows: ["close", "ranged"],
    },
    "vrihedd_brigade_1": {
        name: "Vrihedd Brigade Veteran",
        strength: 5,
        filename: "vrihedd_brigade_1",
        maxPerDeck: 1,
        abilities: ["agile"],
        faction: "scoiatael",
        type: "unit",
        rows: ["close", "ranged"],
    },
    "yaevinn": {
        name: "Yaevinn",
        strength: 6,
        filename: "yaevinn",
        maxPerDeck: 1,
        abilities: ["agile"],
        faction: "scoiatael",
        type: "unit",
        rows: ["close", "ranged"],
    },
    "berserker": {
        name: "Berserker",
        strength: 4,
        filename: "berserker",
        maxPerDeck: 1,
        abilities: ["berserker"],
        faction: "skellige",
        type: "unit",
        rows: ["close"],
    },
    "birna": {
        name: "Birna Bran",
        strength: 2,
        filename: "birna",
        maxPerDeck: 1,
        abilities: ["medic"],
        faction: "skellige",
        type: "unit",
        rows: ["close"],
    },
    "blueboy": {
        name: "Blueboy Lugos",
        strength: 6,
        filename: "blueboy",
        maxPerDeck: 1,
        abilities: [],
        faction: "skellige",
        type: "unit",
        rows: ["close"],
    },
    "cerys": {
        name: "Cerys",
        strength: 10,
        filename: "cerys",
        maxPerDeck: 1,
        abilities: ["hero", "muster"],
        faction: "skellige",
        type: "unit",
        rows: ["close"],
    },
    "brokva_archer": {
        name: "Clan Brokva Archer",
        strength: 6,
        filename: "brokva_archer",
        maxPerDeck: 2,
        abilities: [],
        faction: "skellige",
        type: "unit",
        rows: ["ranged"],
    },
    "dimun_pirate": {
        name: "Clan Dimun Pirate",
        strength: 6,
        filename: "dimun_pirate",
        maxPerDeck: 1,
        abilities: ["scorch"],
        faction: "skellige",
        type: "unit",
        rows: ["ranged"],
    },
    "shield_maiden": {
        name: "Cerys - Clan Drummond Shield Maiden",
        strength: 4,
        filename: "shield_maiden",
        maxPerDeck: 1,
        abilities: ["bond"],
        faction: "skellige",
        type: "unit",
        rows: ["close"],
    },
    "shield_maiden_1": {
        name: "Cerys - Clan Drummond Shield Maiden",
        strength: 4,
        filename: "shield_maiden_1",
        maxPerDeck: 1,
        abilities: ["bond"],
        faction: "skellige",
        type: "unit",
        rows: ["close"],
    },
    "shield_maiden_2": {
        name: "Cerys - Clan Drummond Shield Maiden",
        strength: 4,
        filename: "shield_maiden_2",
        maxPerDeck: 1,
        abilities: ["bond"],
        faction: "skellige",
        type: "unit",
        rows: ["close"],
    },
    "heymaey": {
        name: "Clan Heymaey Skald",
        strength: 4,
        filename: "heymaey",
        maxPerDeck: 1,
        abilities: [],
        faction: "skellige",
        type: "unit",
        rows: ["close"],
    },
    "tordarroch": {
        name: "Clan Tordarroch Armorsmith",
        strength: 4,
        filename: "tordarroch",
        maxPerDeck: 1,
        abilities: [],
        faction: "skellige",
        type: "unit",
        rows: ["close"],
    },
    "craite_warrior": {
        name: "Clan an Craite Warrior",
        strength: 6,
        filename: "craite_warrior",
        maxPerDeck: 3,
        abilities: ["bond"],
        faction: "skellige",
        type: "unit",
        rows: ["close"],
    },
    "donar": {
        name: "Donar an Hindar",
        strength: 4,
        filename: "donar",
        maxPerDeck: 1,
        abilities: [],
        faction: "skellige",
        type: "unit",
        rows: ["close"],
    },
    "draig": {
        name: "Draig Bon-Dhu",
        strength: 2,
        filename: "draig",
        maxPerDeck: 1,
        abilities: ["horn"],
        faction: "skellige",
        type: "unit",
        rows: ["siege"],
    },
    "ermion": {
        name: "Ermion",
        strength: 8,
        filename: "ermion",
        maxPerDeck: 1,
        abilities: ["hero", "mardroeme"],
        faction: "skellige",
        type: "unit",
        rows: ["ranged"],
    },
    "hemdall": {
        name: "Hemdall",
        strength: 11,
        filename: "hemdall",
        maxPerDeck: 0,
        abilities: ["hero"],
        faction: "skellige",
        type: "unit",
        rows: ["close"],
    },
    "hjalmar": {
        name: "Hjalmar",
        strength: 10,
        filename: "hjalmar",
        maxPerDeck: 1,
        abilities: ["hero"],
        faction: "skellige",
        type: "unit",
        rows: ["ranged"],
    },
    "holger": {
        name: "Holger Blackhand",
        strength: 4,
        filename: "holger",
        maxPerDeck: 1,
        abilities: [],
        faction: "skellige",
        type: "unit",
        rows: ["siege"],
    },
    "kambi": {
        name: "Kambi",
        strength: 0,
        filename: "kambi",
        maxPerDeck: 1,
        abilities: ["avenger_kambi"],
        faction: "skellige",
        type: "unit",
        rows: ["close"],
    },
    "light_longship": {
        name: "Light Longship",
        strength: 4,
        filename: "light_longship",
        maxPerDeck: 3,
        abilities: ["muster"],
        faction: "skellige",
        type: "unit",
        rows: ["ranged"],
    },
    "madmad_lugos": {
        name: "Madman Lugos",
        strength: 6,
        filename: "madmad_lugos",
        maxPerDeck: 1,
        abilities: [],
        faction: "skellige",
        type: "unit",
        rows: ["close"],
    },
    "mardroeme": {
        name: "Mardroeme",
        filename: "mardroeme",
        maxPerDeck: 3,
        abilities: ["mardroeme"],
        faction: "neutral",
        type: "special",
        rows: ["close", "ranged", "siege"],
    },
    "olaf": {
        name: "Olaf",
        strength: 12,
        filename: "olaf",
        maxPerDeck: 1,
        abilities: ["agile", "morale"],
        faction: "skellige",
        type: "unit",
        rows: ["close", "ranged"],
    },
    "storm": {
        name: "Skellige Storm",
        filename: "storm",
        maxPerDeck: 3,
        abilities: ["rain", "fog"],
        faction: "neutral",
        type: "weather",
    },
    "svanrige": {
        name: "Svanrige",
        strength: 4,
        filename: "svanrige",
        maxPerDeck: 1,
        abilities: [],
        faction: "skellige",
        type: "unit",
        rows: ["close"],
    },
    "vildkaarl": {
        name: "Transformed Vildkaarl",
        strength: 14,
        filename: "vildkaarl",
        maxPerDeck: 0,
        abilities: ["morale"],
        faction: "skellige",
        type: "unit",
        rows: ["close"],
    },
    "young_vildkaarl": {
        name: "Transformed Young Vildkaarl",
        strength: 8,
        filename: "young_vildkaarl",
        maxPerDeck: 0,
        abilities: ["bond"],
        faction: "skellige",
        type: "unit",
        rows: ["ranged"],
    },
    "udalryk": {
        name: "Udalryk",
        strength: 4,
        filename: "udalryk",
        maxPerDeck: 1,
        abilities: [],
        faction: "skellige",
        type: "unit",
        rows: ["close"],
    },
    "war_longship": {
        name: "War Longship",
        strength: 6,
        filename: "war_longship",
        maxPerDeck: 2,
        abilities: ["bond"],
        faction: "skellige",
        type: "unit",
        rows: ["siege"],
    },
    "young_berserker": {
        name: "Young Berserker",
        strength: 2,
        filename: "young_berserker",
        maxPerDeck: 3,
        abilities: ["berserker"],
        faction: "skellige",
        type: "unit",
        rows: ["ranged"],
    },
    "crach_an_craite": {
        name: "Crach an Craite",
        filename: "crach_an_craite",
        maxPerDeck: 0,
        abilities: ["crach_an_craite"],
        faction: "skellige",
        type: "leader",
    },
    "king_bran": {
        name: "King Bran",
        filename: "king_bran",
        maxPerDeck: 0,
        abilities: ["king_bran"],
        faction: "skellige",
        type: "leader",
    },
    "schirru": {
        name: "Schirru",
        strength: 8,
        filename: "schirru",
        maxPerDeck: 1,
        abilities: ["scorch_s"],
        faction: "scoiatael",
        type: "unit",
        rows: ["siege"],
    },
};

export const cardsArray = Object.values(cards);

export default cards;
