import {maxSpecialAmountPerDeck, minUnitAmountPerDeck} from "./cards.js";
import {CardData} from "./types/card.js";
import type {Deck, SerializedDeck} from "./types/deck.js";
import type {FactionName} from "./types/faction.js";

const isValidFaction = (card: CardData, faction: FactionName): boolean => card.faction === faction || card.faction === "neutral";

export const isValidDeck = (deck: Deck) => {
    if (!isValidFaction(deck.leader, deck.faction) || deck.deck.some((card) => !isValidFaction(card, deck.faction))) {
        return false;
    }

    const unitAmount = deck.deck.filter((card) => card.filename !== "decoy" && card.type === "unit").length;
    const specialAmount = deck.deck.length - unitAmount;

    return unitAmount >= minUnitAmountPerDeck && specialAmount <= maxSpecialAmountPerDeck
};

const premadeDecks: Record<FactionName, SerializedDeck> = {
    realms: {
        leader: "foltest_copper",
        cards: {
            horn: 1,
            decoy: 3,
            frost: 1,
            ciri: 1,
            geralt: 1,
            esterad: 1,
            natalis: 1,
            philippa: 1,
            vernon: 1,
            catapult_1: 2,
            triss: 1,
            villen: 1,
            yennefer: 1,
            ballista: 1,
            olgierd: 1,
            siege_tower: 1,
            trebuchet: 1,
            trebuchet_1: 1,
            crinfrid: 3,
            banner_nurse: 1,
            stennis: 1,
            blue_stripes: 3,
            gaunter_odimm_darkness: 3,
            dijkstra: 1,
            dandelion: 1,
            gaunter_odimm: 1,
            thaler: 1,
            mysterious_elf: 1,
        },
    },
    nilfgaard: {
        leader: "emhyr_gold",
        cards: {
            horn: 1,
            decoy: 3,
            scorch: 1,
            frost: 1,
            clear: 1,
            fog: 1,
            rain: 1,
            ciri: 1,
            geralt: 1,
            black_archer: 1,
            black_archer_1: 1,
            heavy_zerri: 1,
            menno: 1,
            moorvran: 1,
            stefan: 1,
            shilard: 1,
            villen: 1,
            yennefer: 1,
            olgierd: 1,
            young_emissary: 1,
            young_emissary_1: 1,
            gaunter_odimm_darkness: 3,
            vattier: 1,
            imperal_brigade: 4,
            dandelion: 1,
            gaunter_odimm: 1,
            archer_support: 1,
            archer_support_1: 1,
            mysterious_elf: 1,
            siege_support: 1,
        },
    },
    monsters: {
        leader: "eredin_silver",
        cards: {
            horn: 1,
            decoy: 3,
            scorch: 1,
            clear: 1,
            fog: 1,
            rain: 1,
            ciri: 1,
            geralt: 1,
            imlerith: 1,
            kayran: 1,
            toad: 1,
            villen: 1,
            yennefer: 1,
            arachas_behemoth: 1,
            witch_velen: 1,
            witch_velen_1: 1,
            witch_velen_2: 1,
            olgierd: 1,
            katakan: 1,
            arachas: 1,
            arachas_1: 1,
            arachas_2: 1,
            poroniec: 1,
            gaunter_odimm_darkness: 3,
            bruxa: 1,
            ekkima: 1,
            fleder: 1,
            garkain: 1,
            dandelion: 1,
            gaunter_odimm: 1,
            nekker: 1,
            nekker_1: 1,
            nekker_2: 1,
            mysterious_elf: 1,
        },
    },
    scoiatael: {
        leader: "francesca_copper",
        cards: {
            horn: 1,
            decoy: 3,
            scorch: 1,
            frost: 1,
            clear: 1,
            fog: 1,
            rain: 1,
            ciri: 1,
            geralt: 1,
            isengrim: 1,
            milva: 1,
            schirru: 1,
            villen: 1,
            yennefer: 1,
            dol_infantry: 1,
            olgierd: 1,
            havekar_support: 1,
            havekar_support_1: 1,
            havekar_support_2: 1,
            gaunter_odimm_darkness: 3,
            ciaran: 1,
            dwarf: 1,
            dwarf_1: 1,
            dwarf_2: 1,
            dandelion: 1,
            gaunter_odimm: 1,
            havekar_nurse: 1,
            havekar_nurse_1: 1,
            mysterious_elf: 1,
        },
    },
    skellige: {
        leader: "crach_an_craite",
        cards: {
            horn: 1,
            mardroeme: 1,
            scorch: 1,
            frost: 1,
            storm: 1,
            rain: 1,
            ciri: 1,
            geralt: 1,
            olaf: 1,
            cerys: 1,
            ermion: 1,
            villen: 1,
            yennefer: 1,
            craite_warrior: 3,
            dimun_pirate: 1,
            olgierd: 1,
            shield_maiden: 1,
            shield_maiden_1: 1,
            shield_maiden_2: 1,
            light_longship: 3,
            birna: 1,
            dandelion: 1,
            young_berserker: 3,
            kambi: 1,
            mysterious_elf: 1,
        },
    },
};

export default premadeDecks;
