import type {CardData} from "./types/card";

const cards: CardData[] = [
    {
        name: "Mysterious Elf",
        row: "close",
        strength: 0,
        filename: "mysterious_elf",
        maxPerDeck: 1,
        abilities: [
            "hero",
            "spy",
        ],
        faction: "neutral",
        type: "unit",
    },
    {
        name: "Decoy",
        strength: 0,
        filename: "decoy",
        maxPerDeck: 3,
        abilities: [
            "decoy",
        ],
        faction: "neutral",
        type: "special",
    },
    {
        name: "Biting Frost",
        strength: 0,
        filename: "frost",
        maxPerDeck: 3,
        abilities: [
            "frost",
        ],
        faction: "neutral",
        type: "weather",
    },
    {
        name: "Cirilla Fiona Elen Riannon",
        row: "close",
        strength: 15,
        filename: "ciri",
        maxPerDeck: 1,
        abilities: [
            "hero",
        ],
        faction: "neutral",
        type: "unit",
    },
    {
        name: "Clear Weather",
        strength: 0,
        filename: "clear",
        maxPerDeck: 2,
        abilities: [
            "clear",
        ],
        faction: "neutral",
        type: "weather",
    },
    {
        name: "Commander's Horn",
        strength: 0,
        filename: "horn",
        maxPerDeck: 3,
        abilities: [
            "horn",
        ],
        faction: "neutral",
        type: "special",
    },
    {
        name: "Dandelion",
        row: "close",
        strength: 2,
        filename: "dandelion",
        maxPerDeck: 1,
        abilities: [
            "horn",
        ],
        faction: "neutral",
        type: "unit",
    },
    {
        name: "Emiel Regis Rohellec Terzieff",
        row: "close",
        strength: 5,
        filename: "emiel",
        maxPerDeck: 1,
        abilities: [],
        faction: "neutral",
        type: "unit",
    },
    {
        name: "Geralt of Rivia",
        row: "close",
        strength: 15,
        filename: "geralt",
        maxPerDeck: 1,
        abilities: [
            "hero",
        ],
        faction: "neutral",
        type: "unit",
    },
    {
        name: "Impenetrable Fog",
        strength: 0,
        filename: "fog",
        maxPerDeck: 3,
        abilities: [
            "fog",
        ],
        faction: "neutral",
        type: "weather",
    },
    {
        name: "Scorch",
        strength: 0,
        filename: "scorch",
        maxPerDeck: 3,
        abilities: [
            "scorch",
        ],
        faction: "neutral",
        type: "special",
    },
    {
        name: "Torrential Rain",
        strength: 0,
        filename: "rain",
        maxPerDeck: 2,
        abilities: [
            "rain",
        ],
        faction: "neutral",
        type: "weather",
    },
    {
        name: "Triss Merigold",
        row: "close",
        strength: 7,
        filename: "triss",
        maxPerDeck: 1,
        abilities: [
            "hero",
        ],
        faction: "neutral",
        type: "unit",
    },
    {
        name: "Vesemir",
        row: "close",
        strength: 6,
        filename: "vesemir",
        maxPerDeck: 1,
        abilities: [],
        faction: "neutral",
        type: "unit",
    },
    {
        name: "Villentretenmerth",
        row: "close",
        strength: 7,
        filename: "villen",
        maxPerDeck: 1,
        abilities: [
            "scorch_c",
        ],
        faction: "neutral",
        type: "unit",
    },
    {
        name: "Yennefer of Vengerberg",
        row: "ranged",
        strength: 7,
        filename: "yennefer",
        maxPerDeck: 1,
        abilities: [
            "hero",
            "medic",
        ],
        faction: "neutral",
        type: "unit",
    },
    {
        name: "Zoltan Chivay",
        row: "close",
        strength: 5,
        filename: "zoltan",
        maxPerDeck: 1,
        abilities: [],
        faction: "neutral",
        type: "unit",
    },
    {
        name: "Olgierd von Everec",
        row: "agile",
        strength: 6,
        filename: "olgierd",
        maxPerDeck: 1,
        abilities: [
            "agile",
            "morale",
        ],
        faction: "neutral",
        type: "unit",
    },
    {
        name: "Gaunter O'Dimm",
        row: "siege",
        strength: 2,
        filename: "gaunter_odimm",
        maxPerDeck: 1,
        abilities: [
            "muster",
        ],
        faction: "neutral",
        type: "unit",
    },
    {
        name: "Gaunter O'Dimm - Darkness",
        row: "ranged",
        strength: 4,
        filename: "gaunter_odimm_darkness",
        maxPerDeck: 3,
        abilities: [
            "muster",
        ],
        faction: "neutral",
        type: "unit",
    },
    {
        name: "Cow",
        row: "ranged",
        strength: 0,
        filename: "cow",
        maxPerDeck: 1,
        abilities: [
            "avenger",
        ],
        faction: "neutral",
        type: "unit",
    },
    {
        name: "Bovine Defense Force",
        row: "close",
        strength: 8,
        filename: "chort",
        maxPerDeck: 0,
        abilities: [],
        faction: "neutral",
        type: "unit",
    },
    {
        name: "Foltest - King of Temeria",
        strength: 0,
        filename: "foltest_silver",
        maxPerDeck: 1,
        abilities: [
            "foltest_king",
        ],
        faction: "realms",
        type: "leader",
    },
    {
        name: "Foltest - Lord Commander of the North",
        strength: 0,
        filename: "foltest_gold",
        maxPerDeck: 1,
        abilities: [
            "foltest_lord",
        ],
        faction: "realms",
        type: "leader",
    },
    {
        name: "Foltest - The Siegemaster",
        strength: 0,
        filename: "foltest_copper",
        maxPerDeck: 1,
        abilities: [
            "foltest_siegemaster",
        ],
        faction: "realms",
        type: "leader",
    },
    {
        name: "Foltest - The Steel-Forged",
        strength: 0,
        filename: "foltest_bronze",
        maxPerDeck: 1,
        abilities: [
            "foltest_steelforged",
        ],
        faction: "realms",
        type: "leader",
    },
    {
        name: "Foltest - Son of Medell",
        strength: 0,
        filename: "foltest_son_of_medell",
        maxPerDeck: 1,
        abilities: [
            "foltest_son",
        ],
        faction: "realms",
        type: "leader",
    },
    {
        name: "Ballista",
        row: "siege",
        strength: 6,
        filename: "ballista",
        maxPerDeck: 1,
        abilities: [],
        faction: "realms",
        type: "unit",
    },
    {
        name: "Blue Stripes Commando",
        row: "close",
        strength: 4,
        filename: "blue_stripes",
        maxPerDeck: 3,
        abilities: [
            "bond",
        ],
        faction: "realms",
        type: "unit",
    },
    {
        name: "Catapult",
        row: "siege",
        strength: 8,
        filename: "catapult_1",
        maxPerDeck: 2,
        abilities: [
            "bond",
        ],
        faction: "realms",
        type: "unit",
    },
    {
        name: "Crinfrid Reavers Dragon Hunter",
        row: "ranged",
        strength: 5,
        filename: "crinfrid",
        maxPerDeck: 3,
        abilities: [
            "bond",
        ],
        faction: "realms",
        type: "unit",
    },
    {
        name: "Dethmold",
        row: "ranged",
        strength: 6,
        filename: "dethmold",
        maxPerDeck: 1,
        abilities: [],
        faction: "realms",
        type: "unit",
    },
    {
        name: "Dun Banner Medic",
        row: "siege",
        strength: 5,
        filename: "banner_nurse",
        maxPerDeck: 1,
        abilities: [
            "medic",
        ],
        faction: "realms",
        type: "unit",
    },
    {
        name: "Esterad Thyssen",
        row: "close",
        strength: 10,
        filename: "esterad",
        maxPerDeck: 1,
        abilities: [
            "hero",
        ],
        faction: "realms",
        type: "unit",
    },
    {
        name: "John Natalis",
        row: "close",
        strength: 10,
        filename: "natalis",
        maxPerDeck: 1,
        abilities: [
            "hero",
        ],
        faction: "realms",
        type: "unit",
    },
    {
        name: "Kaedweni Siege Expert",
        row: "siege",
        strength: 1,
        filename: "kaedwen_siege",
        maxPerDeck: 1,
        abilities: [
            "morale",
        ],
        faction: "realms",
        type: "unit",
    },
    {
        name: "Kaedweni Siege Expert",
        row: "siege",
        strength: 1,
        filename: "kaedwen_siege_1",
        maxPerDeck: 1,
        abilities: [
            "morale",
        ],
        faction: "realms",
        type: "unit",
    },
    {
        name: "Kaedweni Siege Expert",
        row: "siege",
        strength: 1,
        filename: "kaedwen_siege_2",
        maxPerDeck: 1,
        abilities: [
            "morale",
        ],
        faction: "realms",
        type: "unit",
    },
    {
        name: "Keira Metz",
        row: "ranged",
        strength: 5,
        filename: "keira",
        maxPerDeck: 1,
        abilities: [],
        faction: "realms",
        type: "unit",
    },
    {
        name: "Philippa Eilhart",
        row: "ranged",
        strength: 10,
        filename: "philippa",
        maxPerDeck: 1,
        abilities: [
            "hero",
        ],
        faction: "realms",
        type: "unit",
    },
    {
        name: "Poor Fucking Infantry",
        row: "close",
        strength: 1,
        filename: "poor_infantry",
        maxPerDeck: 4,
        abilities: [
            "bond",
        ],
        faction: "realms",
        type: "unit",
    },
    {
        name: "Prince Stennis",
        row: "close",
        strength: 5,
        filename: "stennis",
        maxPerDeck: 1,
        abilities: [
            "spy",
        ],
        faction: "realms",
        type: "unit",
    },
    {
        name: "Redanian Foot Soldier",
        row: "close",
        strength: 1,
        filename: "redania",
        maxPerDeck: 1,
        abilities: [],
        faction: "realms",
        type: "unit",
    },
    {
        name: "Redanian Foot Soldier",
        row: "close",
        strength: 1,
        filename: "redania_1",
        maxPerDeck: 1,
        abilities: [],
        faction: "realms",
        type: "unit",
    },
    {
        name: "Sheldon Skaggs",
        row: "ranged",
        strength: 4,
        filename: "sheldon",
        maxPerDeck: 1,
        abilities: [],
        faction: "realms",
        type: "unit",
    },
    {
        name: "Siege Tower",
        row: "siege",
        strength: 6,
        filename: "siege_tower",
        maxPerDeck: 1,
        abilities: [],
        faction: "realms",
        type: "unit",
    },
    {
        name: "Siegfried of Denesle",
        row: "close",
        strength: 5,
        filename: "siegfried",
        maxPerDeck: 1,
        abilities: [],
        faction: "realms",
        type: "unit",
    },
    {
        name: "Sigismund Dijkstra",
        row: "close",
        strength: 4,
        filename: "dijkstra",
        maxPerDeck: 1,
        abilities: [
            "spy",
        ],
        faction: "realms",
        type: "unit",
    },
    {
        name: "Síle de Tansarville",
        row: "ranged",
        strength: 5,
        filename: "sheala",
        maxPerDeck: 1,
        abilities: [],
        faction: "realms",
        type: "unit",
    },
    {
        name: "Thaler",
        row: "siege",
        strength: 1,
        filename: "thaler",
        maxPerDeck: 1,
        abilities: [
            "spy",
        ],
        faction: "realms",
        type: "unit",
    },
    {
        name: "Sabrina Glevissig",
        row: "ranged",
        strength: 4,
        filename: "sabrina",
        maxPerDeck: 1,
        abilities: [],
        faction: "realms",
        type: "unit",
    },
    {
        name: "Vernon Roche",
        row: "close",
        strength: 10,
        filename: "vernon",
        maxPerDeck: 1,
        abilities: [
            "hero",
        ],
        faction: "realms",
        type: "unit",
    },
    {
        name: "Ves",
        row: "close",
        strength: 5,
        filename: "ves",
        maxPerDeck: 1,
        abilities: [],
        faction: "realms",
        type: "unit",
    },
    {
        name: "Yarpen Zigrin",
        row: "close",
        strength: 2,
        filename: "yarpen",
        maxPerDeck: 1,
        abilities: [],
        faction: "realms",
        type: "unit",
    },
    {
        name: "Trebuchet",
        row: "siege",
        strength: 6,
        filename: "trebuchet",
        maxPerDeck: 1,
        abilities: [],
        faction: "realms",
        type: "unit",
    },
    {
        name: "Trebuchet",
        row: "siege",
        strength: 6,
        filename: "trebuchet_1",
        maxPerDeck: 1,
        abilities: [],
        faction: "realms",
        type: "unit",
    },
    {
        name: "Emhyr var Emreis - His Imperial Majesty",
        strength: 0,
        filename: "emhyr_silver",
        maxPerDeck: 1,
        abilities: [
            "emhyr_imperial",
        ],
        faction: "nilfgaard",
        type: "leader",
    },
    {
        name: "Emhyr var Emreis - Emperor of Nilfgaard",
        strength: 0,
        filename: "emhyr_copper",
        maxPerDeck: 1,
        abilities: [
            "emhyr_emperor",
        ],
        faction: "nilfgaard",
        type: "leader",
    },
    {
        name: "Emhyr var Emreis - the White Flame",
        strength: 0,
        filename: "emhyr_bronze",
        maxPerDeck: 1,
        abilities: [
            "emhyr_whiteflame",
        ],
        faction: "nilfgaard",
        type: "leader",
    },
    {
        name: "Emhyr var Emreis - The Relentless",
        strength: 0,
        filename: "emhyr_gold",
        maxPerDeck: 1,
        abilities: [
            "emhyr_relentless",
        ],
        faction: "nilfgaard",
        type: "leader",
    },
    {
        name: "Emhyr var Emreis - Invader of the North",
        strength: 0,
        filename: "emhyr_invader_of_the_north",
        maxPerDeck: 1,
        abilities: [
            "emhyr_invader",
        ],
        faction: "nilfgaard",
        type: "leader",
    },
    {
        name: "Albrich",
        row: "ranged",
        strength: 2,
        filename: "albrich",
        maxPerDeck: 1,
        abilities: [],
        faction: "nilfgaard",
        type: "unit",
    },
    {
        name: "Assire var Anahid",
        row: "ranged",
        strength: 6,
        filename: "assire",
        maxPerDeck: 1,
        abilities: [],
        faction: "nilfgaard",
        type: "unit",
    },
    {
        name: "Black Infantry Archer",
        row: "ranged",
        strength: 10,
        filename: "black_archer",
        maxPerDeck: 1,
        abilities: [],
        faction: "nilfgaard",
        type: "unit",
    },
    {
        name: "Black Infantry Archer",
        row: "ranged",
        strength: 10,
        filename: "black_archer_1",
        maxPerDeck: 1,
        abilities: [],
        faction: "nilfgaard",
        type: "unit",
    },
    {
        name: "Cahir Mawr Dyffryn aep Ceallach",
        row: "close",
        strength: 6,
        filename: "cahir",
        maxPerDeck: 1,
        abilities: [],
        faction: "nilfgaard",
        type: "unit",
    },
    {
        name: "Cynthia",
        row: "ranged",
        strength: 4,
        filename: "cynthia",
        maxPerDeck: 1,
        abilities: [],
        faction: "nilfgaard",
        type: "unit",
    },
    {
        name: "Etolian Auxiliary Archers",
        row: "ranged",
        strength: 1,
        filename: "archer_support",
        maxPerDeck: 1,
        abilities: [
            "medic",
        ],
        faction: "nilfgaard",
        type: "unit",
    },
    {
        name: "Etolian Auxiliary Archers",
        row: "ranged",
        strength: 1,
        filename: "archer_support_1",
        maxPerDeck: 1,
        abilities: [
            "medic",
        ],
        faction: "nilfgaard",
        type: "unit",
    },
    {
        name: "Fringilla Vigo",
        row: "ranged",
        strength: 6,
        filename: "fringilla",
        maxPerDeck: 1,
        abilities: [],
        faction: "nilfgaard",
        type: "unit",
    },
    {
        name: "Heavy Zerrikanian Fire Scorpion",
        row: "siege",
        strength: 10,
        filename: "heavy_zerri",
        maxPerDeck: 1,
        abilities: [],
        faction: "nilfgaard",
        type: "unit",
    },
    {
        name: "Impera Brigade Guard",
        row: "close",
        strength: 3,
        filename: "imperal_brigade",
        maxPerDeck: 4,
        abilities: [
            "bond",
        ],
        faction: "nilfgaard",
        type: "unit",
    },
    {
        name: "Letho of Gulet",
        row: "close",
        strength: 10,
        filename: "letho",
        maxPerDeck: 1,
        abilities: [
            "hero",
        ],
        faction: "nilfgaard",
        type: "unit",
    },
    {
        name: "Menno Coehoorn",
        row: "close",
        strength: 10,
        filename: "menno",
        maxPerDeck: 1,
        abilities: [
            "hero",
            "medic",
        ],
        faction: "nilfgaard",
        type: "unit",
    },
    {
        name: "Morteisen",
        row: "close",
        strength: 3,
        filename: "morteisen",
        maxPerDeck: 1,
        abilities: [],
        faction: "nilfgaard",
        type: "unit",
    },
    {
        name: "Morvran Voorhis",
        row: "siege",
        strength: 10,
        filename: "moorvran",
        maxPerDeck: 1,
        abilities: [
            "hero",
        ],
        faction: "nilfgaard",
        type: "unit",
    },
    {
        name: "Nausicaa Cavalry Rider",
        row: "close",
        strength: 2,
        filename: "nauzicaa_2",
        maxPerDeck: 3,
        abilities: [
            "bond",
        ],
        faction: "nilfgaard",
        type: "unit",
    },
    {
        name: "Puttkammer",
        row: "ranged",
        strength: 3,
        filename: "puttkammer",
        maxPerDeck: 1,
        abilities: [],
        faction: "nilfgaard",
        type: "unit",
    },
    {
        name: "Rainfarn",
        row: "close",
        strength: 4,
        filename: "rainfarn",
        maxPerDeck: 1,
        abilities: [],
        faction: "nilfgaard",
        type: "unit",
    },
    {
        name: "Renuald aep Matsen",
        row: "ranged",
        strength: 5,
        filename: "renuald",
        maxPerDeck: 1,
        abilities: [],
        faction: "nilfgaard",
        type: "unit",
    },
    {
        name: "Rotten Mangonel",
        row: "siege",
        strength: 3,
        filename: "rotten",
        maxPerDeck: 1,
        abilities: [],
        faction: "nilfgaard",
        type: "unit",
    },
    {
        name: "Shilard Fitz-Oesterlen",
        row: "close",
        strength: 7,
        filename: "shilard",
        maxPerDeck: 1,
        abilities: [
            "spy",
        ],
        faction: "nilfgaard",
        type: "unit",
    },
    {
        name: "Siege Engineer",
        row: "siege",
        strength: 6,
        filename: "siege_engineer",
        maxPerDeck: 1,
        abilities: [],
        faction: "nilfgaard",
        type: "unit",
    },
    {
        name: "Siege Technician",
        row: "siege",
        strength: 0,
        filename: "siege_support",
        maxPerDeck: 1,
        abilities: [
            "medic",
        ],
        faction: "nilfgaard",
        type: "unit",
    },
    {
        name: "Stefan Skellen",
        row: "close",
        strength: 9,
        filename: "stefan",
        maxPerDeck: 1,
        abilities: [
            "spy",
        ],
        faction: "nilfgaard",
        type: "unit",
    },
    {
        name: "Sweers",
        row: "ranged",
        strength: 2,
        filename: "sweers",
        maxPerDeck: 1,
        abilities: [],
        faction: "nilfgaard",
        type: "unit",
    },
    {
        name: "Tibor Eggebracht",
        row: "ranged",
        strength: 10,
        filename: "tibor",
        maxPerDeck: 1,
        abilities: [
            "hero",
        ],
        faction: "nilfgaard",
        type: "unit",
    },
    {
        name: "Vanhemar",
        row: "ranged",
        strength: 4,
        filename: "vanhemar",
        maxPerDeck: 1,
        abilities: [],
        faction: "nilfgaard",
        type: "unit",
    },
    {
        name: "Vattier de Rideaux",
        row: "close",
        strength: 4,
        filename: "vattier",
        maxPerDeck: 1,
        abilities: [
            "spy",
        ],
        faction: "nilfgaard",
        type: "unit",
    },
    {
        name: "Vreemde",
        row: "close",
        strength: 2,
        filename: "vreemde",
        maxPerDeck: 1,
        abilities: [],
        faction: "nilfgaard",
        type: "unit",
    },
    {
        name: "Young Emissary",
        row: "close",
        strength: 5,
        filename: "young_emissary",
        maxPerDeck: 1,
        abilities: [
            "bond",
        ],
        faction: "nilfgaard",
        type: "unit",
    },
    {
        name: "Young Emissary",
        row: "close",
        strength: 5,
        filename: "young_emissary_1",
        maxPerDeck: 1,
        abilities: [
            "bond",
        ],
        faction: "nilfgaard",
        type: "unit",
    },
    {
        name: "Zerrikanian Fire Scorpion",
        row: "siege",
        strength: 5,
        filename: "zerri",
        maxPerDeck: 1,
        abilities: [],
        faction: "nilfgaard",
        type: "unit",
    },
    {
        name: "Eredin - Commander of the Red Riders",
        strength: 0,
        filename: "eredin_silver",
        maxPerDeck: 1,
        abilities: [
            "eredin_commander",
        ],
        faction: "monsters",
        type: "leader",
    },
    {
        name: "Eredin - Bringer of Death",
        strength: 0,
        filename: "eredin_bronze",
        maxPerDeck: 1,
        abilities: [
            "eredin_bringer_of_death",
        ],
        faction: "monsters",
        type: "leader",
    },
    {
        name: "Eredin - Destroyer of Worlds",
        strength: 0,
        filename: "eredin_gold",
        maxPerDeck: 1,
        abilities: [
            "eredin_destroyer",
        ],
        faction: "monsters",
        type: "leader",
    },
    {
        name: "Eredin - King of the Wild Hunt",
        strength: 0,
        filename: "eredin_copper",
        maxPerDeck: 1,
        abilities: [
            "eredin_king",
        ],
        faction: "monsters",
        type: "leader",
    },
    {
        name: "Eredin Bréacc Glas - The Treacherous",
        strength: 0,
        filename: "eredin_the_treacherous",
        maxPerDeck: 1,
        abilities: [
            "eredin_treacherous",
        ],
        faction: "monsters",
        type: "leader",
    },
    {
        name: "Arachas ",
        row: "close",
        strength: 4,
        filename: "arachas",
        maxPerDeck: 1,
        abilities: [
            "muster",
        ],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Arachas ",
        row: "close",
        strength: 4,
        filename: "arachas_1",
        maxPerDeck: 1,
        abilities: [
            "muster",
        ],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Arachas ",
        row: "close",
        strength: 4,
        filename: "arachas_2",
        maxPerDeck: 1,
        abilities: [
            "muster",
        ],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Arachas- Behemoth",
        row: "siege",
        strength: 6,
        filename: "arachas_behemoth",
        maxPerDeck: 1,
        abilities: [
            "muster",
        ],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Botchling",
        row: "close",
        strength: 4,
        filename: "poroniec",
        maxPerDeck: 1,
        abilities: [],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Celaeno Harpy",
        row: "agile",
        strength: 2,
        filename: "celaeno_harpy",
        maxPerDeck: 1,
        abilities: [
            "agile",
        ],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Cockatrice",
        row: "ranged",
        strength: 2,
        filename: "cockatrice",
        maxPerDeck: 1,
        abilities: [],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Crone - Brewess",
        row: "close",
        strength: 6,
        filename: "witch_velen",
        maxPerDeck: 1,
        abilities: [
            "muster",
        ],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Crone - Weavess",
        row: "close",
        strength: 6,
        filename: "witch_velen_1",
        maxPerDeck: 1,
        abilities: [
            "muster",
        ],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Crone - Whispess",
        row: "close",
        strength: 6,
        filename: "witch_velen_2",
        maxPerDeck: 1,
        abilities: [
            "muster",
        ],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Draug",
        row: "close",
        strength: 10,
        filename: "draug",
        maxPerDeck: 1,
        abilities: [
            "hero",
        ],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Earth Elemental",
        row: "siege",
        strength: 6,
        filename: "earth_elemental",
        maxPerDeck: 1,
        abilities: [],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Endrega",
        row: "ranged",
        strength: 2,
        filename: "endrega",
        maxPerDeck: 1,
        abilities: [],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Fiend",
        row: "close",
        strength: 6,
        filename: "fiend",
        maxPerDeck: 1,
        abilities: [],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Fire Elemental",
        row: "siege",
        strength: 6,
        filename: "fire_elemental",
        maxPerDeck: 1,
        abilities: [],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Foglet",
        row: "close",
        strength: 2,
        filename: "fogling",
        maxPerDeck: 1,
        abilities: [],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Forktail",
        row: "close",
        strength: 5,
        filename: "forktail",
        maxPerDeck: 1,
        abilities: [],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Frightener",
        row: "close",
        strength: 5,
        filename: "frightener",
        maxPerDeck: 1,
        abilities: [],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Gargoyle",
        row: "ranged",
        strength: 2,
        filename: "gargoyle",
        maxPerDeck: 1,
        abilities: [],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Ghoul",
        row: "close",
        strength: 1,
        filename: "ghoul",
        maxPerDeck: 1,
        abilities: [
            "muster",
        ],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Ghoul",
        row: "close",
        strength: 1,
        filename: "ghoul_1",
        maxPerDeck: 1,
        abilities: [
            "muster",
        ],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Ghoul",
        row: "close",
        strength: 1,
        filename: "ghoul_2",
        maxPerDeck: 1,
        abilities: [
            "muster",
        ],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Grave Hag",
        row: "ranged",
        strength: 5,
        filename: "gravehag",
        maxPerDeck: 1,
        abilities: [],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Griffin",
        row: "close",
        strength: 5,
        filename: "gryffin",
        maxPerDeck: 1,
        abilities: [],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Harpy",
        row: "agile",
        strength: 2,
        filename: "harpy",
        maxPerDeck: 1,
        abilities: [
            "agile",
        ],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Ice Giant",
        row: "siege",
        strength: 5,
        filename: "frost_giant",
        maxPerDeck: 1,
        abilities: [],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Imlerith",
        row: "close",
        strength: 10,
        filename: "imlerith",
        maxPerDeck: 1,
        abilities: [
            "hero",
        ],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Kayran",
        row: "agile",
        strength: 8,
        filename: "kayran",
        maxPerDeck: 1,
        abilities: [
            "hero",
            "agile",
            "morale",
        ],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Leshen",
        row: "ranged",
        strength: 10,
        filename: "leshen",
        maxPerDeck: 1,
        abilities: [
            "hero",
        ],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Nekker",
        row: "close",
        strength: 2,
        filename: "nekker",
        maxPerDeck: 1,
        abilities: [
            "muster",
        ],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Nekker",
        row: "close",
        strength: 2,
        filename: "nekker_1",
        maxPerDeck: 1,
        abilities: [
            "muster",
        ],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Nekker",
        row: "close",
        strength: 2,
        filename: "nekker_2",
        maxPerDeck: 1,
        abilities: [
            "muster",
        ],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Plague Maiden",
        row: "close",
        strength: 5,
        filename: "mighty_maiden",
        maxPerDeck: 1,
        abilities: [],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Vampire - Bruxa",
        row: "close",
        strength: 4,
        filename: "bruxa",
        maxPerDeck: 1,
        abilities: [
            "muster",
        ],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Vampire - Ekimmara",
        row: "close",
        strength: 4,
        filename: "ekkima",
        maxPerDeck: 1,
        abilities: [
            "muster",
        ],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Vampire - Fleder",
        row: "close",
        strength: 4,
        filename: "fleder",
        maxPerDeck: 1,
        abilities: [
            "muster",
        ],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Vampire - Garkain",
        row: "close",
        strength: 4,
        filename: "garkain",
        maxPerDeck: 1,
        abilities: [
            "muster",
        ],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Vampire - Katakan",
        row: "close",
        strength: 5,
        filename: "katakan",
        maxPerDeck: 1,
        abilities: [
            "muster",
        ],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Werewolf",
        row: "close",
        strength: 5,
        filename: "werewolf",
        maxPerDeck: 1,
        abilities: [],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Wyvern",
        row: "ranged",
        strength: 2,
        filename: "wyvern",
        maxPerDeck: 1,
        abilities: [],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Toad",
        row: "ranged",
        strength: 7,
        filename: "toad",
        maxPerDeck: 1,
        abilities: [
            "scorch_r",
        ],
        faction: "monsters",
        type: "unit",
    },
    {
        name: "Francesca Findabair - Queen of Dol Blathanna",
        strength: 0,
        filename: "francesca_silver",
        maxPerDeck: 1,
        abilities: [
            "francesca_queen",
        ],
        faction: "scoiatael",
        type: "leader",
    },
    {
        name: "Francesca Findabair - the Beautiful",
        strength: 0,
        filename: "francesca_gold",
        maxPerDeck: 1,
        abilities: [
            "francesca_beautiful",
        ],
        faction: "scoiatael",
        type: "leader",
    },
    {
        name: "Francesca Findabair - Daisy of the Valley",
        strength: 0,
        filename: "francesca_copper",
        maxPerDeck: 1,
        abilities: [
            "francesca_daisy",
        ],
        faction: "scoiatael",
        type: "leader",
    },
    {
        name: "Francesca Findabair - Pureblood Elf",
        strength: 0,
        filename: "francesca_bronze",
        maxPerDeck: 1,
        abilities: [
            "francesca_pureblood",
        ],
        faction: "scoiatael",
        type: "leader",
    },
    {
        name: "Francesca Findabair - Hope of the Aen Seidhe",
        strength: 0,
        filename: "francesca_hope_of_the_aen_seidhe",
        maxPerDeck: 1,
        abilities: [
            "francesca_hope",
        ],
        faction: "scoiatael",
        type: "leader",
    },
    {
        name: "Ciaran aep Easnillien",
        row: "agile",
        strength: 3,
        filename: "ciaran",
        maxPerDeck: 1,
        abilities: [
            "agile",
        ],
        faction: "scoiatael",
        type: "unit",
    },
    {
        name: "Barclay Els",
        row: "agile",
        strength: 6,
        filename: "barclay",
        maxPerDeck: 1,
        abilities: [
            "agile",
        ],
        faction: "scoiatael",
        type: "unit",
    },
    {
        name: "Dennis Cranmer",
        row: "close",
        strength: 6,
        filename: "dennis",
        maxPerDeck: 1,
        abilities: [],
        faction: "scoiatael",
        type: "unit",
    },
    {
        name: "Dol Blathanna Archer",
        row: "ranged",
        strength: 4,
        filename: "dol_archer",
        maxPerDeck: 1,
        abilities: [],
        faction: "scoiatael",
        type: "unit",
    },
    {
        name: "Dol Blathanna Scout",
        row: "agile",
        strength: 6,
        filename: "dol_infantry",
        maxPerDeck: 1,
        abilities: [
            "agile",
        ],
        faction: "scoiatael",
        type: "unit",
    },
    {
        name: "Dol Blathanna Scout",
        row: "agile",
        strength: 6,
        filename: "dol_infantry_1",
        maxPerDeck: 1,
        abilities: [
            "agile",
        ],
        faction: "scoiatael",
        type: "unit",
    },
    {
        name: "Dol Blathanna Scout",
        row: "agile",
        strength: 6,
        filename: "dol_infantry_2",
        maxPerDeck: 1,
        abilities: [
            "agile",
        ],
        faction: "scoiatael",
        type: "unit",
    },
    {
        name: "Dwarven Skirmisher",
        row: "close",
        strength: 3,
        filename: "dwarf",
        maxPerDeck: 1,
        abilities: [
            "muster",
        ],
        faction: "scoiatael",
        type: "unit",
    },
    {
        name: "Dwarven Skirmisher",
        row: "close",
        strength: 3,
        filename: "dwarf_1",
        maxPerDeck: 1,
        abilities: [
            "muster",
        ],
        faction: "scoiatael",
        type: "unit",
    },
    {
        name: "Dwarven Skirmisher",
        row: "close",
        strength: 3,
        filename: "dwarf_2",
        maxPerDeck: 1,
        abilities: [
            "muster",
        ],
        faction: "scoiatael",
        type: "unit",
    },
    {
        name: "Eithné",
        row: "ranged",
        strength: 10,
        filename: "eithne",
        maxPerDeck: 1,
        abilities: [
            "hero",
        ],
        faction: "scoiatael",
        type: "unit",
    },
    {
        name: "Elven Skirmisher",
        row: "ranged",
        strength: 2,
        filename: "elf_skirmisher",
        maxPerDeck: 1,
        abilities: [
            "muster",
        ],
        faction: "scoiatael",
        type: "unit",
    },
    {
        name: "Elven Skirmisher",
        row: "ranged",
        strength: 2,
        filename: "elf_skirmisher_1",
        maxPerDeck: 1,
        abilities: [
            "muster",
        ],
        faction: "scoiatael",
        type: "unit",
    },
    {
        name: "Elven Skirmisher",
        row: "ranged",
        strength: 2,
        filename: "elf_skirmisher_2",
        maxPerDeck: 1,
        abilities: [
            "muster",
        ],
        faction: "scoiatael",
        type: "unit",
    },
    {
        name: "Filavandrel aen Fidhail",
        row: "agile",
        strength: 6,
        filename: "filavandrel",
        maxPerDeck: 1,
        abilities: [
            "agile",
        ],
        faction: "scoiatael",
        type: "unit",
    },
    {
        name: "Havekar Healer",
        row: "ranged",
        strength: 0,
        filename: "havekar_nurse",
        maxPerDeck: 1,
        abilities: [
            "medic",
        ],
        faction: "scoiatael",
        type: "unit",
    },
    {
        name: "Havekar Healer",
        row: "ranged",
        strength: 0,
        filename: "havekar_nurse_1",
        maxPerDeck: 1,
        abilities: [
            "medic",
        ],
        faction: "scoiatael",
        type: "unit",
    },
    {
        name: "Havekar Healer",
        row: "ranged",
        strength: 0,
        filename: "havekar_nurse_2",
        maxPerDeck: 1,
        abilities: [
            "medic",
        ],
        faction: "scoiatael",
        type: "unit",
    },
    {
        name: "Havekar Smuggler",
        row: "close",
        strength: 5,
        filename: "havekar_support",
        maxPerDeck: 1,
        abilities: [
            "muster",
        ],
        faction: "scoiatael",
        type: "unit",
    },
    {
        name: "Havekar Smuggler",
        row: "close",
        strength: 5,
        filename: "havekar_support_1",
        maxPerDeck: 1,
        abilities: [
            "muster",
        ],
        faction: "scoiatael",
        type: "unit",
    },
    {
        name: "Havekar Smuggler",
        row: "close",
        strength: 5,
        filename: "havekar_support_2",
        maxPerDeck: 1,
        abilities: [
            "muster",
        ],
        faction: "scoiatael",
        type: "unit",
    },
    {
        name: "Ida Emean aep Sivney",
        row: "ranged",
        strength: 6,
        filename: "ida",
        maxPerDeck: 1,
        abilities: [],
        faction: "scoiatael",
        type: "unit",
    },
    {
        name: "Iorveth",
        row: "ranged",
        strength: 10,
        filename: "iorveth",
        maxPerDeck: 1,
        abilities: [
            "hero",
        ],
        faction: "scoiatael",
        type: "unit",
    },
    {
        name: "Isengrim Faoiltiarna",
        row: "close",
        strength: 10,
        filename: "isengrim",
        maxPerDeck: 1,
        abilities: [
            "hero",
            "morale",
        ],
        faction: "scoiatael",
        type: "unit",
    },
    {
        name: "Mahakaman Defender",
        row: "close",
        strength: 5,
        filename: "mahakam",
        maxPerDeck: 1,
        abilities: [],
        faction: "scoiatael",
        type: "unit",
    },
    {
        name: "Mahakaman Defender",
        row: "close",
        strength: 5,
        filename: "mahakam_1",
        maxPerDeck: 1,
        abilities: [],
        faction: "scoiatael",
        type: "unit",
    },
    {
        name: "Mahakaman Defender",
        row: "close",
        strength: 5,
        filename: "mahakam_2",
        maxPerDeck: 1,
        abilities: [],
        faction: "scoiatael",
        type: "unit",
    },
    {
        name: "Mahakaman Defender",
        row: "close",
        strength: 5,
        filename: "mahakam_3",
        maxPerDeck: 1,
        abilities: [],
        faction: "scoiatael",
        type: "unit",
    },
    {
        name: "Mahakaman Defender",
        row: "close",
        strength: 5,
        filename: "mahakam_4",
        maxPerDeck: 1,
        abilities: [],
        faction: "scoiatael",
        type: "unit",
    },
    {
        name: "Milva",
        row: "ranged",
        strength: 10,
        filename: "milva",
        maxPerDeck: 1,
        abilities: [
            "morale",
        ],
        faction: "scoiatael",
        type: "unit",
    },
    {
        name: "Riordain",
        row: "ranged",
        strength: 1,
        filename: "riordain",
        maxPerDeck: 1,
        abilities: [],
        faction: "scoiatael",
        type: "unit",
    },
    {
        name: "Saesenthessis",
        row: "ranged",
        strength: 10,
        filename: "saskia",
        maxPerDeck: 1,
        abilities: [
            "hero",
        ],
        faction: "scoiatael",
        type: "unit",
    },
    {
        name: "Toruviel",
        row: "ranged",
        strength: 2,
        filename: "toruviel",
        maxPerDeck: 1,
        abilities: [],
        faction: "scoiatael",
        type: "unit",
    },
    {
        name: "Vrihedd Brigade Recruit",
        row: "ranged",
        strength: 4,
        filename: "vrihedd_cadet",
        maxPerDeck: 1,
        abilities: [],
        faction: "scoiatael",
        type: "unit",
    },
    {
        name: "Vrihedd Brigade Veteran",
        row: "agile",
        strength: 5,
        filename: "vrihedd_brigade",
        maxPerDeck: 1,
        abilities: [
            "agile",
        ],
        faction: "scoiatael",
        type: "unit",
    },
    {
        name: "Vrihedd Brigade Veteran",
        row: "agile",
        strength: 5,
        filename: "vrihedd_brigade_1",
        maxPerDeck: 1,
        abilities: [
            "agile",
        ],
        faction: "scoiatael",
        type: "unit",
    },
    {
        name: "Yaevinn",
        row: "agile",
        strength: 6,
        filename: "yaevinn",
        maxPerDeck: 1,
        abilities: [
            "agile",
        ],
        faction: "scoiatael",
        type: "unit",
    },
    {
        name: "Berserker",
        row: "close",
        strength: 4,
        filename: "berserker",
        maxPerDeck: 1,
        abilities: [
            "berserker",
        ],
        faction: "skellige",
        type: "unit",
    },
    {
        name: "Birna Bran",
        row: "close",
        strength: 2,
        filename: "birna",
        maxPerDeck: 1,
        abilities: [
            "medic",
        ],
        faction: "skellige",
        type: "unit",
    },
    {
        name: "Blueboy Lugos",
        row: "close",
        strength: 6,
        filename: "blueboy",
        maxPerDeck: 1,
        abilities: [],
        faction: "skellige",
        type: "unit",
    },
    {
        name: "Cerys",
        row: "close",
        strength: 10,
        filename: "cerys",
        maxPerDeck: 1,
        abilities: [
            "hero",
            "muster",
        ],
        faction: "skellige",
        type: "unit",
    },
    {
        name: "Clan Brokva Archer",
        row: "ranged",
        strength: 6,
        filename: "brokva_archer",
        maxPerDeck: 2,
        abilities: [],
        faction: "skellige",
        type: "unit",
    },
    {
        name: "Clan Dimun Pirate",
        row: "ranged",
        strength: 6,
        filename: "dimun_pirate",
        maxPerDeck: 1,
        abilities: [
            "scorch",
        ],
        faction: "skellige",
        type: "unit",
    },
    {
        name: "Cerys - Clan Drummond Shield Maiden",
        row: "close",
        strength: 4,
        filename: "shield_maiden",
        maxPerDeck: 1,
        abilities: [
            "bond",
        ],
        faction: "skellige",
        type: "unit",
    },
    {
        name: "Cerys - Clan Drummond Shield Maiden",
        row: "close",
        strength: 4,
        filename: "shield_maiden_1",
        maxPerDeck: 1,
        abilities: [
            "bond",
        ],
        faction: "skellige",
        type: "unit",
    },
    {
        name: "Cerys - Clan Drummond Shield Maiden",
        row: "close",
        strength: 4,
        filename: "shield_maiden_2",
        maxPerDeck: 1,
        abilities: [
            "bond",
        ],
        faction: "skellige",
        type: "unit",
    },
    {
        name: "Clan Heymaey Skald",
        row: "close",
        strength: 4,
        filename: "heymaey",
        maxPerDeck: 1,
        abilities: [],
        faction: "skellige",
        type: "unit",
    },
    {
        name: "Clan Tordarroch Armorsmith",
        row: "close",
        strength: 4,
        filename: "tordarroch",
        maxPerDeck: 1,
        abilities: [],
        faction: "skellige",
        type: "unit",
    },
    {
        name: "Clan an Craite Warrior",
        row: "close",
        strength: 6,
        filename: "craite_warrior",
        maxPerDeck: 3,
        abilities: [
            "bond",
        ],
        faction: "skellige",
        type: "unit",
    },
    {
        name: "Donar an Hindar",
        row: "close",
        strength: 4,
        filename: "donar",
        maxPerDeck: 1,
        abilities: [],
        faction: "skellige",
        type: "unit",
    },
    {
        name: "Draig Bon-Dhu",
        row: "siege",
        strength: 2,
        filename: "draig",
        maxPerDeck: 1,
        abilities: [
            "horn",
        ],
        faction: "skellige",
        type: "unit",
    },
    {
        name: "Ermion",
        row: "ranged",
        strength: 8,
        filename: "ermion",
        maxPerDeck: 1,
        abilities: [
            "hero",
            "mardroeme",
        ],
        faction: "skellige",
        type: "unit",
    },
    {
        name: "Hemdall",
        row: "close",
        strength: 11,
        filename: "hemdall",
        maxPerDeck: 0,
        abilities: [
            "hero",
        ],
        faction: "skellige",
        type: "unit",
    },
    {
        name: "Hjalmar",
        row: "ranged",
        strength: 10,
        filename: "hjalmar",
        maxPerDeck: 1,
        abilities: [
            "hero",
        ],
        faction: "skellige",
        type: "unit",
    },
    {
        name: "Holger Blackhand",
        row: "siege",
        strength: 4,
        filename: "holger",
        maxPerDeck: 1,
        abilities: [],
        faction: "skellige",
        type: "unit",
    },
    {
        name: "Kambi",
        row: "close",
        strength: 0,
        filename: "kambi",
        maxPerDeck: 1,
        abilities: [
            "avenger_kambi",
        ],
        faction: "skellige",
        type: "unit",
    },
    {
        name: "Light Longship",
        row: "ranged",
        strength: 4,
        filename: "light_longship",
        maxPerDeck: 3,
        abilities: [
            "muster",
        ],
        faction: "skellige",
        type: "unit",
    },
    {
        name: "Madman Lugos",
        row: "close",
        strength: 6,
        filename: "madmad_lugos",
        maxPerDeck: 1,
        abilities: [],
        faction: "skellige",
        type: "unit",
    },
    {
        name: "Mardroeme",
        strength: 0,
        filename: "mardroeme",
        maxPerDeck: 3,
        abilities: [
            "mardroeme",
        ],
        faction: "neutral",
        type: "special",
    },
    {
        name: "Olaf",
        row: "agile",
        strength: 12,
        filename: "olaf",
        maxPerDeck: 1,
        abilities: [
            "agile",
            "morale",
        ],
        faction: "skellige",
        type: "unit",
    },
    {
        name: "Skellige Storm",
        strength: 0,
        filename: "storm",
        maxPerDeck: 3,
        abilities: [
            "rain",
            "fog",
        ],
        faction: "neutral",
        type: "weather",
    },
    {
        name: "Svanrige",
        row: "close",
        strength: 4,
        filename: "svanrige",
        maxPerDeck: 1,
        abilities: [],
        faction: "skellige",
        type: "unit",
    },
    {
        name: "Transformed Vildkaarl",
        row: "close",
        strength: 14,
        filename: "vildkaarl",
        maxPerDeck: 0,
        abilities: [
            "morale",
        ],
        faction: "skellige",
        type: "unit",
    },
    {
        name: "Transformed Young Vildkaarl",
        row: "ranged",
        strength: 8,
        filename: "young_vildkaarl",
        maxPerDeck: 0,
        abilities: [
            "bond",
        ],
        faction: "skellige",
        type: "unit",
    },
    {
        name: "Udalryk",
        row: "close",
        strength: 4,
        filename: "udalryk",
        maxPerDeck: 1,
        abilities: [],
        faction: "skellige",
        type: "unit",
    },
    {
        name: "War Longship",
        row: "siege",
        strength: 6,
        filename: "war_longship",
        maxPerDeck: 2,
        abilities: [
            "bond",
        ],
        faction: "skellige",
        type: "unit",
    },
    {
        name: "Young Berserker",
        row: "ranged",
        strength: 2,
        filename: "young_berserker",
        maxPerDeck: 3,
        abilities: [
            "berserker",
        ],
        faction: "skellige",
        type: "unit",
    },
    {
        name: "Crach an Craite",
        strength: 0,
        filename: "crach_an_craite",
        maxPerDeck: 0,
        abilities: [
            "crach_an_craite",
        ],
        faction: "skellige",
        type: "leader",
    },
    {
        name: "King Bran",
        strength: 0,
        filename: "king_bran",
        maxPerDeck: 0,
        abilities: [
            "king_bran",
        ],
        faction: "skellige",
        type: "leader",
    },
    {
        name: "Schirru",
        row: "siege",
        strength: 8,
        filename: "schirru",
        maxPerDeck: 1,
        abilities: [
            "scorch_s",
        ],
        faction: "scoiatael",
        type: "unit",
    },
];

export default cards;
